import { useEffect, useState } from 'react'
import { BadgeCheck, CalendarDays, Megaphone, Tag } from 'lucide-react'
import toast from 'react-hot-toast'
import { supabase } from '../../lib/supabase'
import { useAuth } from '../../contexts/AuthContext'
import EmptyState from '../../components/ui/EmptyState'
import Spinner from '../../components/ui/Spinner'

export default function MerchantCampaigns() {
  const { user } = useAuth(); const [campaigns, setCampaigns] = useState([]); const [joined, setJoined] = useState(new Set()); const [loading, setLoading] = useState(true)
  const load = async () => { setLoading(true); const now = new Date().toISOString(); const [campaignResult, joinedResult] = await Promise.all([supabase.from('campaigns').select('*').eq('is_active', true).gte('ends_at', now).order('starts_at'), supabase.from('merchant_campaigns').select('campaign_id').eq('merchant_id', user.id)]); if (campaignResult.error || joinedResult.error) toast.error(campaignResult.error?.message || joinedResult.error?.message); setCampaigns(campaignResult.data || []); setJoined(new Set((joinedResult.data || []).map((row) => row.campaign_id))); setLoading(false) }
  useEffect(() => { if (user) load() }, [user?.id])
  const join = async (campaignId) => { const { error } = await supabase.from('merchant_campaigns').insert({ campaign_id: campaignId, merchant_id: user.id }); if (error) return toast.error(error.message); toast.success('Your store joined the campaign!'); load() }
  return <div className="mx-auto max-w-6xl p-4 sm:p-6 lg:p-8"><div className="mb-6"><p className="text-xs font-bold uppercase tracking-[0.16em] text-teal-600">Grow your sales</p><h1 className="mt-1 font-display text-2xl font-bold text-ink">Marketplace Campaigns</h1><p className="mt-1 max-w-2xl text-sm leading-6 text-ink/50">Join an admin campaign to apply its discount to every active product in your store. Your product quantity discounts automatically pause while the campaign is live.</p></div>{loading ? <div className="flex justify-center py-24"><Spinner /></div> : campaigns.length === 0 ? <div className="card"><EmptyState icon={Megaphone} title="No available campaigns" message="New marketplace campaigns will appear here." /></div> : <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{campaigns.map((campaign) => { const hasJoined = joined.has(campaign.id); const upcoming = Date.now() < new Date(campaign.starts_at).getTime(); return <article key={campaign.id} className={`overflow-hidden rounded-2xl border bg-white shadow-soft ${hasJoined ? 'border-teal-300 ring-2 ring-teal-500/10' : 'border-black/[0.06]'}`}><div className="bg-gradient-to-br from-teal-900 to-teal-600 p-5 text-white"><div className="flex items-center justify-between"><Tag size={22} className="text-mango-300" />{hasJoined && <span className="badge gap-1 bg-white/15 text-white"><BadgeCheck size={13} /> Joined</span>}</div><p className="mt-5 font-display text-4xl font-bold text-mango-300">{Number(campaign.discount_percent)}% OFF</p><h2 className="mt-2 font-display text-lg font-bold">{campaign.name}</h2></div><div className="p-5"><p className="min-h-[3rem] text-sm leading-6 text-ink/55">{campaign.description || 'Apply this campaign discount to all your products.'}</p><div className="mt-4 rounded-xl bg-cream p-3 text-xs leading-5 text-ink/55"><p className="flex items-center gap-2 font-semibold text-ink/70"><CalendarDays size={14} />{upcoming ? 'Starts' : 'Ends'} {new Date(upcoming ? campaign.starts_at : campaign.ends_at).toLocaleString()}</p></div><button onClick={() => join(campaign.id)} disabled={hasJoined} className="btn-primary mt-4 w-full disabled:bg-teal-100 disabled:text-teal-700">{hasJoined ? 'Already joined' : 'Join campaign'}</button></div></article> })}</div>}</div>
}
