import { useEffect, useState } from 'react'
import { Clock3, Loader2, Save, UserRound, WalletCards } from 'lucide-react'
import toast from 'react-hot-toast'
import { supabase } from '../lib/supabase'
import { useAuth } from '../contexts/AuthContext'
import { cleanText } from '../utils/security'

export default function AccountSettings({ merchant = false }) {
  const { user, profile, refreshProfile } = useAuth()
  const business = profile?.merchant_profiles
  const [saving,setSaving]=useState(false)
  const [form,setForm]=useState({ full_name:'',phone:'',payout_method:'bank',payout_provider:'',payout_account_name:'',payout_account_number:'',business_name:'',business_description:'',store_open_time:'09:00',store_close_time:'18:00',auto_pause_outside_hours:false })
  useEffect(()=>setForm(current=>({ ...current,full_name:profile?.full_name||'',phone:profile?.phone||'',payout_method:profile?.payout_method||'bank',payout_provider:profile?.payout_provider||'',payout_account_name:profile?.payout_account_name||profile?.full_name||'',payout_account_number:profile?.payout_account_number||'',business_name:business?.business_name||'',business_description:business?.business_description||'',store_open_time:(business?.store_open_time||'09:00').slice(0,5),store_close_time:(business?.store_close_time||'18:00').slice(0,5),auto_pause_outside_hours:Boolean(business?.auto_pause_outside_hours) })),[profile,business])
  const update=field=>event=>setForm(current=>({...current,[field]:event.target.type==='checkbox'?event.target.checked:event.target.value}))
  const save=async event=>{event.preventDefault();if(form.full_name.trim().length<2)return toast.error('Enter your complete name.');if(form.payout_account_number&&(!form.payout_provider.trim()||!form.payout_account_name.trim()))return toast.error('Complete your payout provider and account name.');setSaving(true);const profileResult=await supabase.from('profiles').update({full_name:cleanText(form.full_name,160),phone:cleanText(form.phone,30),payout_method:cleanText(form.payout_method,30),payout_provider:cleanText(form.payout_provider,80),payout_account_name:cleanText(form.payout_account_name,160),payout_account_number:cleanText(form.payout_account_number,80)}).eq('id',user.id);let merchantResult={error:null};if(merchant&&!profileResult.error)merchantResult=await supabase.from('merchant_profiles').update({business_name:cleanText(form.business_name,160),business_description:cleanText(form.business_description,1000),store_open_time:form.store_open_time||null,store_close_time:form.store_close_time||null,auto_pause_outside_hours:form.auto_pause_outside_hours,store_timezone:'Asia/Manila'}).eq('id',user.id);setSaving(false);const error=profileResult.error||merchantResult.error;if(error)return toast.error(error.message);await refreshProfile();toast.success('Account settings updated.')}
  return <div className="mx-auto max-w-3xl p-4 sm:p-6 lg:p-8"><form onSubmit={save} className="space-y-5"><section className="rounded-3xl border border-black/[.06] bg-white p-6 shadow-soft"><UserRound className="text-teal-700"/><h1 className="mt-3 font-display text-2xl font-bold text-ink">Update {merchant?'Merchant':'Reseller'} Account</h1><p className="mt-1 text-sm text-ink/50">Keep your contact and payout information accurate.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold text-ink/70">Full name<input required maxLength="160" value={form.full_name} onChange={update('full_name')} className="input-field mt-1"/></label><label className="text-sm font-semibold text-ink/70">Phone<input maxLength="30" value={form.phone} onChange={update('phone')} className="input-field mt-1"/></label>{merchant&&<><label className="text-sm font-semibold text-ink/70">Business name<input required maxLength="160" value={form.business_name} onChange={update('business_name')} className="input-field mt-1"/></label><label className="text-sm font-semibold text-ink/70 sm:col-span-2">Business description<textarea rows="3" maxLength="1000" value={form.business_description} onChange={update('business_description')} className="input-field mt-1 resize-none"/></label></>}</div></section>
  <section className="rounded-3xl border border-black/[.06] bg-white p-6 shadow-soft"><WalletCards className="text-mango-700"/><h2 className="mt-3 font-display text-xl font-bold">Withdrawal destination</h2><p className="mt-1 text-xs leading-5 text-ink/50">Approved withdrawals will be sent to this bank or e-wallet. You can still confirm the destination before each request.</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold text-ink/70">Destination type<select value={form.payout_method} onChange={update('payout_method')} className="input-field mt-1"><option value="bank">Bank</option><option value="ewallet">E-wallet</option></select></label><label className="text-sm font-semibold text-ink/70">Bank or e-wallet<input maxLength="80" value={form.payout_provider} onChange={update('payout_provider')} placeholder="BPI, BDO, GCash, Maya" className="input-field mt-1"/></label><label className="text-sm font-semibold text-ink/70">Account name<input maxLength="160" value={form.payout_account_name} onChange={update('payout_account_name')} className="input-field mt-1"/></label><label className="text-sm font-semibold text-ink/70">Account number<input maxLength="80" value={form.payout_account_number} onChange={update('payout_account_number')} className="input-field mt-1"/></label></div></section>
  {merchant&&<section className="rounded-3xl border border-black/[.06] bg-white p-6 shadow-soft"><Clock3 className="text-teal-700"/><h2 className="mt-3 font-display text-xl font-bold">Optional store hours</h2><p className="mt-1 text-xs leading-5 text-ink/50">When enabled, all active products become unavailable outside these daily Asia/Manila hours. Your individual product settings are preserved.</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold text-ink/70">Opening time<input type="time" value={form.store_open_time} onChange={update('store_open_time')} className="input-field mt-1"/></label><label className="text-sm font-semibold text-ink/70">Closing time<input type="time" value={form.store_close_time} onChange={update('store_close_time')} className="input-field mt-1"/></label></div><label className="mt-4 flex items-start gap-3 rounded-2xl bg-teal-50 p-4 text-sm text-ink/65"><input type="checkbox" checked={form.auto_pause_outside_hours} onChange={update('auto_pause_outside_hours')} className="mt-1 accent-teal-700"/><span><strong className="block text-teal-900">Automatically pause all products while closed</strong>Leave unchecked if your store accepts orders 24/7.</span></label></section>}
  <button disabled={saving} className="btn-primary flex w-full items-center justify-center gap-2 py-3"><>{saving?<Loader2 className="animate-spin" size={17}/>:<Save size={17}/>}</>{saving?'Saving...':'Save account settings'}</button></form></div>
}
