import { useEffect, useMemo, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { ArrowLeft, FileText, ShieldCheck } from 'lucide-react'
import { supabase } from '../lib/supabase'
import Spinner from '../components/ui/Spinner'
import { applyCurrentBrand } from '../utils/brand'

const labels = { terms: 'Terms of Service', privacy: 'Privacy Policy', merchant: 'Merchant Agreement', reseller: 'Reseller Agreement', commission: 'Commission Policy', refund: 'Refund and Dispute Policy', cookie: 'Cookie Policy', acceptable_use: 'Acceptable Use Policy', termination: 'Account Suspension and Termination Policy' }
function safeHtml(value = '') { const doc = new DOMParser().parseFromString(value, 'text/html'); doc.querySelectorAll('script,style,iframe,object,embed,form,link,meta').forEach(n => n.remove()); doc.querySelectorAll('*').forEach(n => [...n.attributes].forEach(a => { if (a.name.startsWith('on') || /javascript:/i.test(a.value)) n.removeAttribute(a.name) })); return doc.body.innerHTML }

export default function Policy({ defaultType = 'privacy' }) {
  const { type: routeType } = useParams(); const type = labels[routeType] ? routeType : defaultType
  const [policy, setPolicy] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const content = useMemo(() => safeHtml(policy?.content), [policy?.content])
  useEffect(() => { let active = true; async function load() { setLoading(true); setError(''); const today = new Date().toISOString().slice(0, 10); const { data, error: e } = await supabase.from('system_policies').select('*').eq('policy_type', type).eq('status', 'published').lte('effective_date', today).order('effective_date', { ascending: false }).order('created_at', { ascending: false }).limit(1).maybeSingle(); if (active) { setPolicy(data ? applyCurrentBrand(data) : null); setError(e?.message || (!data ? 'No published policy is currently available.' : '')); setLoading(false) } } load(); return () => { active = false } }, [type])
  return <div className="min-h-[70vh] bg-bg"><header className="bg-teal-950 text-white"><div className="mx-auto max-w-5xl px-4 py-10 sm:px-6 sm:py-14"><Link to="/" className="inline-flex items-center gap-2 text-sm font-semibold text-white/65 hover:text-white"><ArrowLeft size={16}/> Back to JOM HUB</Link><div className="mt-6 flex items-start gap-4"><div className="rounded-2xl bg-white/10 p-3"><ShieldCheck size={25}/></div><div><p className="text-xs font-bold uppercase tracking-[.18em] text-green-200">Legal & transparency</p><h1 className="mt-2 font-display text-3xl font-bold sm:text-5xl">{policy?.title || labels[type]}</h1>{policy && <p className="mt-3 text-sm text-white/55">Version {policy.version} · Effective {new Date(`${policy.effective_date}T00:00:00`).toLocaleDateString('en-PH', { dateStyle: 'long' })} · Last updated {new Date(policy.updated_at).toLocaleDateString('en-PH', { dateStyle: 'long' })}</p>}</div></div></div></header><main className="mx-auto max-w-5xl px-4 py-8 sm:px-6 sm:py-12">{loading ? <div className="flex justify-center py-20"><Spinner/></div> : error ? <div className="rounded-2xl border border-coral-200 bg-surface p-8 text-center"><FileText className="mx-auto text-coral-500"/><h2 className="mt-3 font-display text-xl font-bold">Policy unavailable</h2><p className="mt-2 text-sm text-ink/60">{error}</p></div> : <article className="legal-content rounded-2xl border border-black/[.06] bg-surface p-5 shadow-card sm:p-10" dangerouslySetInnerHTML={{ __html: content }}/>}</main></div>
}
