import { useEffect, useState } from 'react'
import { ArrowDown, ArrowUp, Eye, EyeOff, Image, LayoutTemplate, Loader2, Monitor, Plus, Save, Smartphone, Trash2, X } from 'lucide-react'
import toast from 'react-hot-toast'
import { supabase } from '../../lib/supabase'
import { applyCurrentBrand } from '../../utils/brand'

const defaults = {
  eyebrow: 'Built for growing Filipino businesses', title: 'Grow your wholesale business in one trusted marketplace.',
  description: 'JOM HUB brings merchants and resellers together with product sourcing, secure wallet payments, order tracking, business reports, and direct communication.',
  hero_image: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1400&q=85',
  hero_button: 'Start your business', hero_border: 'rounded', hero_accent: '#16794B',
  announcement: { enabled: true, text: 'Welcome to JOM HUB — Built for growing Filipino businesses', link_text: 'Join now', link_url: '/signup', background: '#0B4D30', color: '#FFFFFF' },
  banners: [],
  sections: { benefits: true, process: true, subscription: true, topup: true, final_cta: true }
}

const emptyBanner = () => ({ id: crypto.randomUUID(), title: 'New promotional banner', text: 'Add your campaign message or important announcement here.', button_label: 'Learn more', button_link: '/catalog', image_url: '', background: '#ECF8EF', text_color: '#142019', border_color: '#D4EFDA', border_width: 1, border_style: 'solid', radius: '24', visible: true })

function Field({ label, children }) { return <label className="block text-xs font-semibold text-ink/65">{label}{children}</label> }

function HeroPreview({ value, mobile }) {
  const radius = value.hero_border === 'square' ? '0' : value.hero_border === 'soft' ? '12px' : '28px'
  return <div className={`mx-auto overflow-hidden bg-surface-inset shadow-xl transition-all ${mobile ? 'w-[320px]' : 'w-full'}`}><div style={{ background: value.announcement.background, color: value.announcement.color }} className={`px-4 py-2 text-center text-[10px] font-semibold ${value.announcement.enabled ? '' : 'hidden'}`}>{value.announcement.text}</div><div className={`grid gap-5 p-6 ${mobile ? '' : 'grid-cols-2 items-center'}`}><div><span className="text-[9px] font-bold uppercase tracking-wider" style={{ color: value.hero_accent }}>{value.eyebrow}</span><h2 className={`${mobile ? 'text-xl' : 'text-2xl'} mt-2 font-display font-bold leading-tight text-ink`}>{value.title}</h2><p className="mt-2 text-[10px] leading-5 text-ink/55">{value.description}</p><span className="mt-3 inline-block rounded-lg px-3 py-2 text-[10px] font-bold text-white" style={{ background: value.hero_accent }}>{value.hero_button}</span></div><div className="aspect-[4/3] overflow-hidden bg-teal-50" style={{ borderRadius: radius, border: `1px solid ${value.hero_accent}30` }}>{value.hero_image ? <img src={value.hero_image} className="h-full w-full object-cover" alt="Hero preview" /> : <div className="flex h-full items-center justify-center"><Image className="text-teal-300" /></div>}</div></div>{value.banners.filter((banner) => banner.visible).map((banner) => <div key={banner.id} className="mx-6 mb-4 p-4" style={{ background: banner.background, color: banner.text_color, border: `${banner.border_width}px ${banner.border_style} ${banner.border_color}`, borderRadius: `${banner.radius}px` }}><p className="text-sm font-bold">{banner.title}</p><p className="mt-1 text-[9px] opacity-70">{banner.text}</p></div>)}</div>
}

export default function HomepageEditor() {
  const [form, setForm] = useState(defaults)
  const [selected, setSelected] = useState('hero')
  const [saving, setSaving] = useState(false)
  const [mobilePreview, setMobilePreview] = useState(false)
  const [previewOpen, setPreviewOpen] = useState(false)

  useEffect(() => { supabase.from('site_settings').select('value').eq('key', 'home').maybeSingle().then(({ data }) => { if (data?.value) { const value = applyCurrentBrand(data.value); setForm({ ...defaults, ...value, announcement: { ...defaults.announcement, ...value.announcement }, sections: { ...defaults.sections, ...value.sections }, banners: value.banners || [] }) } }) }, [])
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }))
  const updateAnnouncement = (key, value) => setForm((current) => ({ ...current, announcement: { ...current.announcement, [key]: value } }))
  const updateBanner = (id, key, value) => setForm((current) => ({ ...current, banners: current.banners.map((banner) => banner.id === id ? { ...banner, [key]: value } : banner) }))
  const moveBanner = (index, direction) => setForm((current) => { const banners = [...current.banners]; const target = index + direction; if (target < 0 || target >= banners.length) return current; [banners[index], banners[target]] = [banners[target], banners[index]]; return { ...current, banners } })
  const addBanner = () => { const banner = emptyBanner(); setForm((current) => ({ ...current, banners: [...current.banners, banner] })); setSelected(banner.id) }
  const removeBanner = (id) => { setForm((current) => ({ ...current, banners: current.banners.filter((banner) => banner.id !== id) })); setSelected('hero') }
  const save = async () => { setSaving(true); const { error } = await supabase.from('site_settings').upsert({ key: 'home', value: form }, { onConflict: 'key' }); setSaving(false); if (error) return toast.error(error.message); toast.success('Homepage published successfully.') }
  const activeBanner = form.banners.find((banner) => banner.id === selected)

  return <div className="min-h-[calc(100vh-4rem)] bg-bg">
    <div className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-black/10 bg-surface px-4 shadow-sm sm:px-6"><div className="flex min-w-0 items-center gap-3"><LayoutTemplate className="shrink-0 text-teal-600" size={21} /><div className="min-w-0"><h1 className="truncate font-display font-bold text-ink">Homepage Designer</h1><p className="hidden text-xs text-ink/45 sm:block">Customize sections and publish your storefront</p></div></div><div className="flex items-center gap-2"><button onClick={() => setPreviewOpen(true)} className="btn-secondary flex items-center gap-2 px-3 py-2 text-xs xl:hidden"><Eye size={15} /> Preview</button><button onClick={save} disabled={saving} className="btn-primary flex items-center gap-2 px-4 py-2 text-sm">{saving ? <Loader2 size={16} className="animate-spin" /> : <Save size={16} />}{saving ? 'Publishing...' : 'Publish'}</button></div></div>
    <div className="grid min-h-[calc(100vh-8rem)] lg:grid-cols-[240px_360px_1fr]">
      <aside className="border-r border-black/10 bg-surface p-3"><p className="px-3 py-2 text-[10px] font-bold uppercase tracking-[0.16em] text-ink/40">Homepage sections</p><button onClick={() => setSelected('announcement')} className={`mt-1 flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-semibold ${selected === 'announcement' ? 'bg-teal-50 text-teal-800' : 'text-ink/65 hover:bg-black/[0.03]'}`}><span className="h-6 w-8 rounded bg-teal-900" /> Announcement bar</button><button onClick={() => setSelected('hero')} className={`mt-1 flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-semibold ${selected === 'hero' ? 'bg-teal-50 text-teal-800' : 'text-ink/65 hover:bg-black/[0.03]'}`}><Image size={18} className="text-teal-600" /> Hero section</button>
        <div className="mt-3 border-t border-black/5 pt-3">{form.banners.map((banner, index) => <div key={banner.id} className={`mb-1 flex items-center rounded-xl ${selected === banner.id ? 'bg-teal-50' : 'hover:bg-black/[0.03]'}`}><button onClick={() => setSelected(banner.id)} className="min-w-0 flex-1 px-3 py-3 text-left"><p className="truncate text-sm font-semibold text-ink/70">{banner.title}</p><p className="text-[10px] text-ink/40">Promotional banner</p></button><div className="mr-2 flex"><button onClick={() => moveBanner(index, -1)} disabled={!index} className="p-1 text-ink/35 disabled:opacity-20"><ArrowUp size={13} /></button><button onClick={() => moveBanner(index, 1)} disabled={index === form.banners.length - 1} className="p-1 text-ink/35 disabled:opacity-20"><ArrowDown size={13} /></button></div></div>)}</div><button onClick={addBanner} className="mt-2 flex w-full items-center justify-center gap-2 rounded-xl border-2 border-dashed border-teal-200 px-3 py-3 text-xs font-bold text-teal-700 hover:bg-teal-50"><Plus size={15} /> Add banner</button>
        <p className="mt-6 px-3 py-2 text-[10px] font-bold uppercase tracking-[0.16em] text-ink/40">Built-in sections</p>{Object.entries(form.sections).map(([key, visible]) => <button key={key} onClick={() => setForm((current) => ({ ...current, sections: { ...current.sections, [key]: !visible } }))} className="flex w-full items-center justify-between rounded-lg px-3 py-2 text-xs font-semibold capitalize text-ink/60 hover:bg-black/[0.03]"><span>{key.replace('_', ' ')}</span>{visible ? <Eye size={14} className="text-teal-600" /> : <EyeOff size={14} className="text-ink/30" />}</button>)}</aside>

      <section className="border-r border-black/10 bg-surface p-5 overflow-y-auto">
        {selected === 'announcement' && <div className="space-y-4"><h2 className="font-display font-bold text-ink">Announcement bar</h2><label className="flex items-center justify-between text-sm font-semibold text-ink/65">Show announcement <input type="checkbox" checked={form.announcement.enabled} onChange={(e) => updateAnnouncement('enabled', e.target.checked)} /></label><Field label="Message"><input className="input-field mt-1" value={form.announcement.text} onChange={(e) => updateAnnouncement('text', e.target.value)} maxLength={180} /></Field><Field label="Link label"><input className="input-field mt-1" value={form.announcement.link_text} onChange={(e) => updateAnnouncement('link_text', e.target.value)} /></Field><Field label="Link URL"><input className="input-field mt-1" value={form.announcement.link_url} onChange={(e) => updateAnnouncement('link_url', e.target.value)} /></Field><div className="grid grid-cols-2 gap-3"><Field label="Background"><input type="color" className="mt-1 h-11 w-full rounded-lg" value={form.announcement.background} onChange={(e) => updateAnnouncement('background', e.target.value)} /></Field><Field label="Text"><input type="color" className="mt-1 h-11 w-full rounded-lg" value={form.announcement.color} onChange={(e) => updateAnnouncement('color', e.target.value)} /></Field></div></div>}
        {selected === 'hero' && <div className="space-y-4"><h2 className="font-display font-bold text-ink">Hero section</h2><Field label="Eyebrow"><input className="input-field mt-1" value={form.eyebrow} onChange={(e) => update('eyebrow', e.target.value)} /></Field><Field label="Headline"><textarea rows={3} className="input-field mt-1" value={form.title} onChange={(e) => update('title', e.target.value)} /></Field><Field label="Description"><textarea rows={4} className="input-field mt-1" value={form.description} onChange={(e) => update('description', e.target.value)} /></Field><Field label="Button label"><input className="input-field mt-1" value={form.hero_button} onChange={(e) => update('hero_button', e.target.value)} /></Field><Field label="Hero image URL"><input className="input-field mt-1" value={form.hero_image} onChange={(e) => update('hero_image', e.target.value)} /></Field><Field label="Image border style"><select className="input-field mt-1" value={form.hero_border} onChange={(e) => update('hero_border', e.target.value)}><option value="rounded">Large rounded</option><option value="soft">Soft rounded</option><option value="square">Square</option></select></Field><Field label="Brand accent"><input type="color" className="mt-1 h-11 w-full rounded-lg" value={form.hero_accent} onChange={(e) => update('hero_accent', e.target.value)} /></Field></div>}
        {activeBanner && <div className="space-y-4"><div className="flex items-center justify-between"><h2 className="font-display font-bold text-ink">Edit banner</h2><button onClick={() => removeBanner(activeBanner.id)} className="rounded-lg bg-coral-100 p-2 text-coral-600"><Trash2 size={16} /></button></div><label className="flex items-center justify-between text-sm font-semibold text-ink/65">Visible <input type="checkbox" checked={activeBanner.visible} onChange={(e) => updateBanner(activeBanner.id, 'visible', e.target.checked)} /></label><Field label="Title"><input className="input-field mt-1" value={activeBanner.title} onChange={(e) => updateBanner(activeBanner.id, 'title', e.target.value)} /></Field><Field label="Description"><textarea rows={3} className="input-field mt-1" value={activeBanner.text} onChange={(e) => updateBanner(activeBanner.id, 'text', e.target.value)} /></Field><Field label="Optional image URL"><input className="input-field mt-1" value={activeBanner.image_url} onChange={(e) => updateBanner(activeBanner.id, 'image_url', e.target.value)} /></Field><div className="grid grid-cols-2 gap-3"><Field label="Button"><input className="input-field mt-1" value={activeBanner.button_label} onChange={(e) => updateBanner(activeBanner.id, 'button_label', e.target.value)} /></Field><Field label="Button link"><input className="input-field mt-1" value={activeBanner.button_link} onChange={(e) => updateBanner(activeBanner.id, 'button_link', e.target.value)} /></Field></div><div className="grid grid-cols-3 gap-2"><Field label="Background"><input type="color" className="mt-1 h-10 w-full" value={activeBanner.background} onChange={(e) => updateBanner(activeBanner.id, 'background', e.target.value)} /></Field><Field label="Text"><input type="color" className="mt-1 h-10 w-full" value={activeBanner.text_color} onChange={(e) => updateBanner(activeBanner.id, 'text_color', e.target.value)} /></Field><Field label="Border"><input type="color" className="mt-1 h-10 w-full" value={activeBanner.border_color} onChange={(e) => updateBanner(activeBanner.id, 'border_color', e.target.value)} /></Field></div><div className="grid grid-cols-3 gap-2"><Field label="Border width"><input type="number" min="0" max="8" className="input-field mt-1 px-2" value={activeBanner.border_width} onChange={(e) => updateBanner(activeBanner.id, 'border_width', e.target.value)} /></Field><Field label="Border type"><select className="input-field mt-1 px-2" value={activeBanner.border_style} onChange={(e) => updateBanner(activeBanner.id, 'border_style', e.target.value)}><option>solid</option><option>dashed</option><option>dotted</option><option>double</option></select></Field><Field label="Corner radius"><input type="number" min="0" max="60" className="input-field mt-1 px-2" value={activeBanner.radius} onChange={(e) => updateBanner(activeBanner.id, 'radius', e.target.value)} /></Field></div></div>}
      </section>

      <section className="hidden p-6 xl:block"><div className="mb-4 flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-wider text-ink/40">Live preview</p><div className="flex rounded-lg bg-surface p-1 shadow-sm"><button onClick={() => setMobilePreview(false)} className={`rounded-md p-2 ${!mobilePreview ? 'bg-teal-50 text-teal-700' : 'text-ink/35'}`}><Monitor size={16} /></button><button onClick={() => setMobilePreview(true)} className={`rounded-md p-2 ${mobilePreview ? 'bg-teal-50 text-teal-700' : 'text-ink/35'}`}><Smartphone size={16} /></button></div></div><HeroPreview value={form} mobile={mobilePreview} /></section>
    </div>
    {previewOpen && <div className="fixed inset-0 z-50 overflow-y-auto bg-scrim/60 p-4 backdrop-blur-sm"><div className="mx-auto max-w-4xl"><div className="mb-3 flex justify-end"><button onClick={() => setPreviewOpen(false)} className="rounded-full bg-surface p-2 text-ink"><X size={20} /></button></div><HeroPreview value={form} mobile={false} /></div></div>}
  </div>
}
