import { useEffect, useState } from 'react'
import { Archive, Download, Eye, FileCode2, Plus, RotateCcw, Save, Send, X } from 'lucide-react'
import toast from 'react-hot-toast'
import { supabase } from '../../lib/supabase'
import { useAuth } from '../../contexts/AuthContext'
import Spinner from '../../components/ui/Spinner'

const types = { terms:'Terms of Service', privacy:'Privacy Policy', merchant:'Merchant Agreement', reseller:'Reseller Agreement', commission:'Commission Policy', refund:'Refund and Dispute Policy', cookie:'Cookie Policy', acceptable_use:'Acceptable Use Policy', termination:'Suspension and Termination' }
const blank = { policy_type:'terms', version:'1.0', title:types.terms, content:'<h2>1. Section title</h2><p>Policy content...</p>', effective_date:new Date().toISOString().slice(0,10), status:'draft' }
const safeHtml = (value='') => { const doc=new DOMParser().parseFromString(value,'text/html'); doc.querySelectorAll('script,style,iframe,object,embed,form,link,meta').forEach(node=>node.remove()); doc.querySelectorAll('*').forEach(node=>[...node.attributes].forEach(attr=>{if(attr.name.startsWith('on')||/javascript:/i.test(attr.value))node.removeAttribute(attr.name)})); return doc.body.innerHTML }
export default function LegalSettings() {
 const { profile }=useAuth(); const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[form,setForm]=useState(null),[preview,setPreviewState]=useState(null),[saving,setSaving]=useState(false)
 const setPreview=(value)=>setPreviewState(value?{...value,content:safeHtml(value.content),title:safeHtml(value.title),version:safeHtml(value.version)}:null)
 const load=async()=>{setLoading(true);const{data,error}=await supabase.from('system_policies').select('*').order('policy_type').order('created_at',{ascending:false});if(error)toast.error(error.message);setRows(data||[]);setLoading(false)}; useEffect(()=>{load()},[])
 const save=async e=>{e.preventDefault();setSaving(true);const payload={policy_type:form.policy_type,version:form.version.trim(),title:form.title.trim(),content:form.content,effective_date:form.effective_date,status:form.status||'draft',created_by:form.created_by||profile?.id,updated_at:new Date().toISOString()};const result=form.id?await supabase.from('system_policies').update(payload).eq('id',form.id):await supabase.from('system_policies').insert(payload);setSaving(false);if(result.error)return toast.error(result.error.message);toast.success('Policy saved.');setForm(null);load()}
 const publish=async row=>{if(!confirm(`Publish ${row.title} version ${row.version}?`))return;const{error}=await supabase.rpc('publish_system_policy',{target_id:row.id});if(error)return toast.error(error.message);toast.success('Policy published.');load()}
 const archive=async row=>{if(!confirm('Archive this version?'))return;const{error}=await supabase.from('system_policies').update({status:'archived',updated_at:new Date().toISOString()}).eq('id',row.id);if(error)return toast.error(error.message);toast.success('Version archived.');load()}
 const restore=row=>setForm({...row,id:undefined,version:`${row.version}-restored-${new Date().toISOString().slice(0,10)}`,status:'draft',created_by:profile?.id})
 const html=row=>`<!doctype html><html><head><meta charset="utf-8"><title>RM Hub Policy</title><style>body{font:16px/1.65 Arial;max-width:850px;margin:40px auto;padding:20px;color:#16211e}h1,h2{color:#0b5b46}</style></head><body><h1>${safeHtml(row.title)}</h1><p>Version ${safeHtml(row.version)} · Effective ${safeHtml(row.effective_date)}</p>${safeHtml(row.content)}<hr><small>© ${new Date().getFullYear()} RM Hub</small></body></html>`
 const exportHtml=row=>{const url=URL.createObjectURL(new Blob([html(row)],{type:'text/html'}));const a=document.createElement('a');a.href=url;a.download=`${row.policy_type}-v${row.version}.html`;a.click();URL.revokeObjectURL(url)}
 const exportPdf=row=>{const w=window.open('','_blank');if(!w)return toast.error('Allow pop-ups to export PDF.');w.document.write(html(row));w.document.close();w.focus();setTimeout(()=>w.print(),250)}
 if(loading)return <div className="flex justify-center py-24"><Spinner/></div>
 return <div className="mx-auto max-w-6xl px-4 py-8 sm:px-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="font-display text-2xl font-bold">Legal Settings</h1><p className="mt-1 text-sm text-ink/55">Manage published policies and complete version history.</p></div><button className="btn-primary inline-flex items-center justify-center gap-2" onClick={()=>setForm({...blank})}><Plus size={17}/> Add Policy</button></div><div className="mt-6 overflow-hidden rounded-2xl border border-black/[.06] bg-white shadow-card"><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-teal-50 text-xs uppercase text-teal-900"><tr><th className="p-4">Policy</th><th className="p-4">Version</th><th className="p-4">Effective</th><th className="p-4">Status</th><th className="p-4 text-right">Actions</th></tr></thead><tbody>{rows.map(row=><tr key={row.id} className="border-t border-black/5"><td className="p-4 font-semibold">{row.title}<p className="text-xs font-normal text-ink/45">{types[row.policy_type]}</p></td><td className="p-4">{row.version}</td><td className="p-4 whitespace-nowrap">{row.effective_date}</td><td className="p-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${row.status==='published'?'bg-green-100 text-green-800':row.status==='archived'?'bg-slate-100 text-slate-600':'bg-mango-100 text-mango-700'}`}>{row.status}</span></td><td className="p-4"><div className="flex justify-end gap-1"><button title="Edit" onClick={()=>setForm(row)} className="rounded-lg p-2 hover:bg-teal-50"><Save size={16}/></button><button title="Preview" onClick={()=>setPreview(row)} className="rounded-lg p-2 hover:bg-teal-50"><Eye size={16}/></button>{row.status!=='published'&&<button title="Publish" onClick={()=>publish(row)} className="rounded-lg p-2 text-teal-700 hover:bg-teal-50"><Send size={16}/></button>}{row.status!=='archived'&&<button title="Archive" onClick={()=>archive(row)} className="rounded-lg p-2"><Archive size={16}/></button>}<button title="Restore as draft" onClick={()=>restore(row)} className="rounded-lg p-2"><RotateCcw size={16}/></button><button title="Export HTML" onClick={()=>exportHtml(row)} className="rounded-lg p-2"><FileCode2 size={16}/></button><button title="Print / Save PDF" onClick={()=>exportPdf(row)} className="rounded-lg p-2"><Download size={16}/></button></div></td></tr>)}</tbody></table></div></div>
 {form&&<div className="fixed inset-0 z-[80] overflow-y-auto bg-ink/55 p-3 sm:p-6"><form onSubmit={save} className="mx-auto max-w-4xl rounded-2xl bg-white p-5 shadow-2xl sm:p-7"><div className="flex justify-between"><h2 className="font-display text-xl font-bold">{form.id?'Edit Policy':'New Policy Version'}</h2><button type="button" onClick={()=>setForm(null)}><X/></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Policy type<select className="input-field mt-1" value={form.policy_type} onChange={e=>setForm({...form,policy_type:e.target.value,title:form.id?form.title:types[e.target.value]})}>{Object.entries(types).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="text-sm font-semibold">Version<input required className="input-field mt-1" value={form.version} onChange={e=>setForm({...form,version:e.target.value})}/></label><label className="text-sm font-semibold sm:col-span-2">Title<input required className="input-field mt-1" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="text-sm font-semibold">Effective date<input required type="date" className="input-field mt-1" value={form.effective_date} onChange={e=>setForm({...form,effective_date:e.target.value})}/></label><label className="text-sm font-semibold">Status<select className="input-field mt-1" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label><label className="text-sm font-semibold sm:col-span-2">Content (HTML)<textarea required rows="16" className="input-field mt-1 font-mono text-xs" value={form.content} onChange={e=>setForm({...form,content:e.target.value})}/></label></div><div className="mt-5 flex justify-end gap-3"><button type="button" className="btn-secondary" onClick={()=>setPreview(form)}>Preview</button><button disabled={saving} className="btn-primary">{saving?'Saving…':'Save Policy'}</button></div></form></div>}
 {preview&&<div className="fixed inset-0 z-[90] overflow-y-auto bg-ink/55 p-3 sm:p-6"><div className="mx-auto max-w-4xl rounded-2xl bg-white p-5 shadow-2xl sm:p-8"><div className="flex justify-between"><div><h2 className="font-display text-2xl font-bold">{preview.title}</h2><p className="text-xs text-ink/50">Version {preview.version} · Effective {preview.effective_date}</p></div><button onClick={()=>setPreview(null)}><X/></button></div><article className="legal-content mt-7" dangerouslySetInnerHTML={{__html:preview.content}}/></div></div>}</div>
}
