import { useEffect,useState } from 'react'
import { ShieldAlert } from 'lucide-react'
import toast from 'react-hot-toast'
import { supabase } from '../../lib/supabase'
import EmptyState from '../../components/ui/EmptyState'
import Spinner from '../../components/ui/Spinner'
import { formatDate } from '../../utils/format'

export default function OrderCases(){const[items,setItems]=useState([]),[loading,setLoading]=useState(true);const load=async()=>{setLoading(true);const{data,error}=await supabase.from('order_cases').select('*,orders(order_number,status,merchant_id,reseller_id)').order('created_at',{ascending:false});if(error)toast.error(error.message);setItems(data||[]);setLoading(false)};useEffect(()=>{load()},[]);const review=async(item,approve)=>{const notes=window.prompt(approve?'Enter the approved resolution:':'Enter the reason for rejection:');if(notes===null)return;const{error}=await supabase.rpc('review_order_case',{p_case_id:item.id,p_approve:approve,p_notes:notes});if(error)return toast.error(error.message);toast.success('Case resolved successfully.');load()};if(loading)return <div className="py-24"><Spinner/></div>;return <div className="mx-auto max-w-4xl px-4 py-8"><h1 className="font-display text-2xl font-bold">Order Cases</h1><p className="mt-1 text-sm text-ink/50">Cancellation, dispute, return, replacement, and refund requests.</p><div className="mt-6 space-y-3">{items.length?items.map(item=><article key={item.id} className="card p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-bold capitalize">{item.case_type} · {item.orders?.order_number}</p><p className="text-xs text-ink/45">Opened {formatDate(item.created_at)} · Order {item.orders?.status}</p></div><span className="badge bg-mango-100 text-mango-700 capitalize">{item.status.replace('_',' ')}</span></div><p className="mt-3 text-sm leading-6 text-ink/65">{item.reason}</p>{item.resolution_notes&&<p className="mt-3 rounded-xl bg-teal-50 p-3 text-xs text-teal-800">Resolution: {item.resolution_notes}</p>}{['open','merchant_review','admin_review'].includes(item.status)&&<div className="mt-4 flex gap-2"><button onClick={()=>review(item,true)} className="btn-primary text-xs">Approve and resolve</button><button onClick={()=>review(item,false)} className="btn-secondary text-xs">Reject request</button></div>}</article>):<EmptyState icon={ShieldAlert} title="No order cases" message="New requests will appear here."/>}</div></div>}
