-- =====================================================================
-- Purchase Order Module (TASK8.md) — audit artifact, not a second
-- order system.
--
-- TASK8.md asks for a distinct "Purchase Order Module" between Reseller
-- and Merchant: create a PO, send it to the Merchant, keep PO history
-- and PO status. Every order in this app already necessarily has both
-- reseller_id and merchant_id set (orders.reseller_id/merchant_id are
-- both NOT NULL — a Reseller is always the buyer from a Merchant, a
-- Customer is just who it ships to), so "Reseller confirms an order to
-- a Merchant" and "an order is created" are already the same event here.
--
-- Rather than inventing a second creation/approval workflow (which
-- would duplicate quote_order/place_order and violate BUSINESS_RULES.md's
-- "money-moving logic lives only in existing security definer RPCs"),
-- this adds a purely additive 1:1 audit row per order, auto-generated by
-- a trigger — giving Resellers/Merchants a PO number and PO history view
-- without a second place that creates or mutates order state.
--
-- Deliberately has NO independent status column. A separate PO status
-- (open/fulfilled/cancelled) duplicated from orders.status would drift
-- the moment one write path updates one and not the other — exactly the
-- two-sources-of-truth failure shape BUSINESS_RULES.md's Security Rules
-- section already documents an incident about (the referral_appointments
-- direct-grant bug). "PO status" is always read live via a join to
-- orders.status instead.
-- =====================================================================

create table if not exists public.purchase_orders (
  id uuid primary key default gen_random_uuid(),
  po_number text not null unique,
  order_id uuid not null unique references public.orders(id) on delete cascade,
  reseller_id uuid not null references public.profiles(id) on delete cascade,
  merchant_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists idx_purchase_orders_reseller on public.purchase_orders(reseller_id, created_at desc);
create index if not exists idx_purchase_orders_merchant on public.purchase_orders(merchant_id, created_at desc);

alter table public.purchase_orders enable row level security;

drop policy if exists "purchase_orders_party_read" on public.purchase_orders;
create policy "purchase_orders_party_read" on public.purchase_orders
  for select to authenticated using (
    reseller_id = auth.uid() or merchant_id = auth.uid() or public.is_admin()
  );

-- No insert/update/delete grants to anyone — every row is written solely
-- by the trigger below, which runs as the table owner (same posture as
-- the existing order_number auto-assign trigger).
grant select on public.purchase_orders to authenticated;

-- ---------------------------------------------------------------------
-- assign_purchase_order — fires once per new order, generates a PO
-- number in the same style orders.order_number already uses ('ORD-'
-- prefix -> 'PO-' prefix), and links it 1:1 to the order. Never blocks
-- or rejects the order insert (a PO row is a record of the order, not a
-- gate on it) — any failure here would need to not break checkout, but
-- there is no plausible failure mode: reseller_id/merchant_id are
-- already NOT NULL and FK-valid by the time this fires.
-- ---------------------------------------------------------------------
create or replace function public.assign_purchase_order()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.purchase_orders (po_number, order_id, reseller_id, merchant_id)
  values (
    'PO-' || to_char(now(), 'YYMMDD') || '-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 6)),
    new.id, new.reseller_id, new.merchant_id
  )
  on conflict (order_id) do nothing;
  return new;
end;
$$;

drop trigger if exists trg_assign_purchase_order on public.orders;
create trigger trg_assign_purchase_order after insert on public.orders
for each row execute function public.assign_purchase_order();

-- ---------------------------------------------------------------------
-- Backfill — every order that already exists gets a PO row too, so
-- "PO history" isn't empty/inconsistent for accounts with existing
-- order history the moment this ships.
-- ---------------------------------------------------------------------
insert into public.purchase_orders (po_number, order_id, reseller_id, merchant_id, created_at)
select
  'PO-' || to_char(o.created_at, 'YYMMDD') || '-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 6)),
  o.id, o.reseller_id, o.merchant_id, o.created_at
from public.orders o
where not exists (select 1 from public.purchase_orders po where po.order_id = o.id);

-- ---------------------------------------------------------------------
-- get_purchase_orders — one RPC for both the Reseller and Merchant PO
-- history views, joining live order status/total rather than storing a
-- duplicate. p_role_filter lets the same RPC serve "POs I sent"
-- (reseller) and "POs I received" (merchant) without two functions.
-- ---------------------------------------------------------------------
create or replace function public.get_purchase_orders(p_limit int default 50, p_offset int default 0)
returns table (
  id uuid,
  po_number text,
  order_id uuid,
  order_number text,
  reseller_id uuid,
  merchant_id uuid,
  order_status public.order_status,
  total numeric,
  created_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select po.id, po.po_number, po.order_id, o.order_number, po.reseller_id, po.merchant_id, o.status, o.total, po.created_at
  from public.purchase_orders po
  join public.orders o on o.id = po.order_id
  where po.reseller_id = auth.uid() or po.merchant_id = auth.uid() or public.is_admin()
  order by po.created_at desc
  limit greatest(1, least(coalesce(p_limit, 50), 200))
  offset greatest(0, coalesce(p_offset, 0));
$$;

grant execute on function public.get_purchase_orders(int, int) to authenticated;

notify pgrst, 'reload schema';
