import { useEffect, useState } from 'react'
import { createPortal } from 'react-dom'
import { BookOpenCheck, ChevronRight } from 'lucide-react'
import { useLocation } from 'react-router-dom'

const labelOf=(element,fallback='Control')=>(element?.getAttribute('aria-label')||element?.getAttribute('placeholder')||element?.getAttribute('title')||element?.textContent||fallback).trim().replace(/\s+/g,' ').slice(0,90)
const instructionFor=(element,label)=>{
  if(element.matches('[data-guide-current-nav]'))return `This is the active “${label}” menu. Select it to return to this page.`
  if(element.matches('h1,h2'))return `This is the “${label}” section. Start here before using the page actions.`
  if(element.matches('select'))return `Select “${label}” and choose the correct option.`
  if(element.matches('textarea'))return `Enter complete and accurate information in “${label}”.`
  if(element.matches('input[type="checkbox"],input[type="radio"]'))return `Select “${label}” when it applies.`
  if(element.matches('input'))return `Enter the correct ${label.toLowerCase()} here and verify it before saving.`
  if(element.matches('a'))return `Select “${label}” to open this page or action.`
  return `Select “${label}” to perform this action.`
}

export default function InteractivePageGuide(){
  const{pathname}=useLocation();const[open,setOpen]=useState(false);const[index,setIndex]=useState(0);const[tour,setTour]=useState([]);const[position,setPosition]=useState({opacity:0});const[arrow,setArrow]=useState({side:'top',left:24})
  const collect=()=>{const main=document.querySelector('[data-guide-main]'),visible=element=>element&&element.offsetParent!==null&&!element.disabled&&!element.closest('[data-guide-walkthrough]'),elements=[];const nav=document.querySelector('[data-guide-current-nav]');if(visible(nav))elements.push(nav);const heading=main?.querySelector('h1')||main?.querySelector('h2');if(visible(heading))elements.push(heading);main?.querySelectorAll('button,a[href],input:not([type="hidden"]),select,textarea').forEach(element=>{if(visible(element)&&elements.length<22)elements.push(element)});const bell=document.querySelector('[data-guide-notifications] button');if(visible(bell))elements.push(bell);return[...new Set(elements)].map((element,step)=>{const label=labelOf(element,`Control ${step+1}`);return{element,label,instruction:instructionFor(element,label)}})}
  const start=()=>{setTour(collect());setIndex(0);setPosition({opacity:0});setOpen(true)}
  useEffect(()=>{if(open){setTour(collect());setIndex(0);setPosition({opacity:0})}},[pathname])
  useEffect(()=>{const target=tour[index]?.element;if(!open||!target||!document.contains(target))return;const old={outline:target.style.outline,outlineOffset:target.style.outlineOffset,boxShadow:target.style.boxShadow,position:target.style.position,zIndex:target.style.zIndex,borderRadius:target.style.borderRadius};target.style.outline='4px solid #FFB238';target.style.outlineOffset='6px';target.style.boxShadow='0 0 0 9999px rgba(3,33,22,.44),0 0 0 12px rgba(255,178,56,.25),0 20px 50px rgba(3,33,22,.35)';if(getComputedStyle(target).position==='static')target.style.position='relative';target.style.zIndex='88';target.style.borderRadius=target.style.borderRadius||'12px';target.scrollIntoView({behavior:'smooth',block:'center',inline:'center'});if(target.matches('input,select,textarea'))setTimeout(()=>target.focus({preventScroll:true}),300)
    const place=()=>{const rect=target.getBoundingClientRect(),width=Math.min(384,window.innerWidth-16),height=205,gap=15;let left=Math.min(window.innerWidth-width-8,Math.max(8,rect.left+rect.width/2-width/2));const below=window.innerHeight-rect.bottom>=height+gap||rect.top<height+gap;const top=below?rect.bottom+gap:Math.max(8,rect.top-height-gap);setArrow({side:below?'top':'bottom',left:Math.max(20,Math.min(width-32,rect.left+rect.width/2-left))});setPosition({left:`${left}px`,top:`${top}px`,width:`${width}px`,right:'auto',bottom:'auto',opacity:1})};const timer=setTimeout(place,340);window.addEventListener('resize',place);window.addEventListener('scroll',place,true);return()=>{clearTimeout(timer);window.removeEventListener('resize',place);window.removeEventListener('scroll',place,true);Object.assign(target.style,old)}},[open,index,tour])
  const current=tour[index],next=()=>index>=tour.length-1?setOpen(false):(setPosition({opacity:0}),setIndex(value=>value+1))
  const card=open&&current?<div data-guide-walkthrough style={position} className="fixed z-[100] max-h-[min(300px,46vh)] overflow-y-auto rounded-2xl border border-mango-300 bg-white shadow-2xl transition-opacity" role="dialog" aria-labelledby="guide-title"><span style={{left:`${arrow.left}px`}} className={`absolute z-20 h-4 w-4 rotate-45 border-mango-300 bg-white ${arrow.side==='top'?'-top-2 border-l border-t':'-bottom-2 border-b border-r'}`}/><header className="sticky top-0 z-10 bg-gradient-to-r from-teal-950 to-teal-700 px-4 py-3 text-white"><p className="text-[9px] font-extrabold uppercase tracking-[.16em] text-mango-300">Selected control · {index+1}/{tour.length}</p><h2 id="guide-title" className="mt-1 font-display text-sm font-bold">{current.label}</h2></header><div className="p-3"><p className="rounded-xl border border-mango-200 bg-mango-100/70 px-3 py-2.5 text-xs leading-5 text-ink/70">{current.instruction}</p><div className="mt-3 grid grid-cols-3 gap-2"><button disabled={index===0} onClick={()=>{setPosition({opacity:0});setIndex(value=>value-1)}} className="btn-secondary py-2 text-xs disabled:opacity-35">Back</button><button onClick={()=>setOpen(false)} className="rounded-xl border border-coral-200 bg-coral-50 px-2 py-2 text-xs font-bold text-coral-600 hover:bg-coral-100">Cancel</button><button onClick={next} className="btn-primary flex items-center justify-center gap-1 py-2 text-xs">{index===tour.length-1?'Finish':'Next'}{index<tour.length-1&&<ChevronRight size={14}/>}</button></div></div></div>:null
  return <><button type="button" onClick={start} className="flex h-10 items-center gap-2 rounded-xl border border-black/[.06] bg-white px-3 text-sm font-bold text-teal-700 shadow-sm transition hover:bg-teal-50" aria-label="Open button-by-button guide"><BookOpenCheck size={18}/><span className="hidden sm:inline">Guide</span></button>{card&&createPortal(card,document.body)}</>
}
