create table if not exists public.system_policies (
  id uuid primary key default gen_random_uuid(),
  policy_type text not null check (policy_type in ('terms','privacy','merchant','reseller','commission','refund','cookie','acceptable_use','termination')),
  version text not null,
  title text not null,
  content text not null,
  effective_date date not null,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  created_by uuid references public.profiles(id),
  status text not null default 'draft' check (status in ('draft','published','archived')),
  unique(policy_type,version)
);
create index if not exists system_policies_latest_idx on public.system_policies(policy_type,status,effective_date desc,created_at desc);
create unique index if not exists system_policies_one_published_idx on public.system_policies(policy_type) where status='published';
alter table public.system_policies enable row level security;
drop policy if exists "system_policies_public_read" on public.system_policies;
create policy "system_policies_public_read" on public.system_policies for select using (status='published' or public.is_admin());
drop policy if exists "system_policies_admin_manage" on public.system_policies;
create policy "system_policies_admin_manage" on public.system_policies for all to authenticated using(public.is_admin()) with check(public.is_admin());
grant select on public.system_policies to anon,authenticated;
grant insert,update,delete on public.system_policies to authenticated;

create or replace function public.publish_system_policy(target_id uuid)
returns public.system_policies language plpgsql security definer set search_path=public as $$
declare selected public.system_policies;
begin
  if not public.is_admin() then raise exception 'Administrator access required'; end if;
  select * into selected from public.system_policies where id=target_id for update;
  if selected.id is null then raise exception 'Policy version not found'; end if;
  update public.system_policies set status='archived',updated_at=now() where policy_type=selected.policy_type and status='published' and id<>target_id;
  update public.system_policies set status='published',updated_at=now() where id=target_id returning * into selected;
  return selected;
end $$;
revoke all on function public.publish_system_policy(uuid) from public;
grant execute on function public.publish_system_policy(uuid) to authenticated;

insert into public.system_policies(policy_type,version,title,content,effective_date,status)
values
('terms','1.0','Terms of Service',$policy$
<h2>1. Agreement and Platform Role</h2><p>These Terms govern access to RM Hub. RM Hub operates a digital marketplace that connects independent Merchants and Resellers. RM Hub is not the seller, manufacturer, owner, or custodian of listed inventory unless a listing expressly states otherwise. The Merchant is the seller of record and remains responsible for listings, product legality, quality, safety, warranty, taxes, shipping, fulfillment, returns, and customer remedies.</p>
<h2>2. Eligibility and Accounts</h2><p>Users must be at least eighteen years old, legally capable of contracting, provide accurate information, secure their email account, and promptly update business details. Approval may require identity, business, permit, and payment verification.</p>
<h2>3. Transactions</h2><p>Merchants must provide accurate prices, stock, identity, promotional conditions, and legally required product information. Resellers must accurately represent products and must not make warranties or claims not authorized by the Merchant. Orders are contracts between the relevant Merchant and buyer or Reseller, subject to applicable law.</p>
<h2>4. Fees and Platform Powers</h2><p>RM Hub may charge disclosed subscriptions, commissions, and service fees. RM Hub may review listings, preserve evidence, restrict transactions, cooperate with authorities, and suspend accounts for risk, fraud, illegality, or policy violations.</p>
<h2>5. Disclaimers and Liability</h2><p>To the maximum extent permitted by law, RM Hub does not guarantee product quality, merchantability, fitness, availability, delivery time, or user conduct. Nothing excludes liability or consumer rights that cannot lawfully be excluded. Users remain liable for their own acts, representations, taxes, and contracts.</p>
<h2>6. Governing Law</h2><p>These Terms are governed by Philippine law. Parties should first use the platform dispute process. Claims may be brought before the proper Philippine courts or agencies with jurisdiction.</p>$policy$,'2026-07-21','published'),
('privacy','1.0','Privacy Policy',$policy$
<h2>1. Scope and Controller</h2><p>RM Hub processes personal data in accordance with Republic Act No. 10173, its IRR, and applicable National Privacy Commission issuances. Contact the designated privacy contact at support@tindahub.ph.</p>
<h2>2. Data Collected</h2><p>We process identity and contact details, verified email, account role, business and permit information, addresses, product and customer records, orders, messages, reviews, wallet and payment evidence, payout details, device logs, and support communications.</p>
<h2>3. Purposes and Legal Bases</h2><p>Data is processed to perform contracts, authenticate users, review accounts, operate marketplace and financial workflows, prevent fraud, comply with law, resolve disputes, secure the service, and pursue legitimate business interests. Consent is obtained when required.</p>
<h2>4. Sharing and Retention</h2><p>Necessary data may be shared with transaction participants, authorized staff, hosting, authentication, storage, email and payment providers, professional advisers, and lawful authorities. Data is retained only as necessary for transactions, accounting, security, legal claims, and statutory duties, then deleted, anonymized, or securely isolated.</p>
<h2>5. Rights and Security</h2><p>Data subjects may exercise rights to information, access, correction, objection, erasure or blocking, portability where applicable, damages, and complaint before the NPC, subject to lawful limitations. RM Hub uses access control, private storage, logging, review workflows, and reasonable organizational and technical safeguards.</p>
<h2>6. Contact</h2><p>Privacy requests may be sent to support@tindahub.ph with sufficient information to verify identity and locate the relevant records.</p>$policy$,'2026-07-21','published'),
('merchant','1.0','Merchant Agreement',$policy$<h2>1. Appointment</h2><p>The Merchant appoints RM Hub as a non-exclusive marketplace technology provider. No agency, partnership, employment, franchise, or ownership of inventory is created.</p><h2>2. Merchant Duties</h2><p>The Merchant is the seller of record and warrants that it is properly registered where required; has authority to sell each product; maintains permits and truthful identity details; provides accurate product, price, stock, warranty, promotional, and return information; issues legally required documents; fulfills orders; protects customer data; and complies with consumer, tax, product-safety, intellectual-property, and e-commerce laws.</p><h2>3. Reseller Network</h2><p>The Merchant authorizes approved Resellers to promote listings using accurate information. The Merchant must honor accepted orders and disclosed reseller pricing, subject to stock and lawful cancellation rules.</p><h2>4. Fees and Enforcement</h2><p>Subscriptions and commissions are governed by the published Commission Policy. RM Hub may delist products, hold payouts under review, request evidence, or suspend access for complaints, counterfeit goods, unsafe products, fraud, or legal risk.</p><h2>5. Indemnity</h2><p>To the extent permitted by law, the Merchant is responsible for claims arising from its products, listings, fulfillment, warranties, taxes, infringement, or misconduct.</p>$policy$,'2026-07-21','published'),
('reseller','1.0','Reseller Agreement',$policy$<h2>1. Independent Reseller</h2><p>A Reseller is an independent marketplace user, not an employee or agent of RM Hub or a Merchant. No guaranteed income, territory, customer volume, or profit is promised.</p><h2>2. Permitted Activity</h2><p>Resellers may select approved products, create truthful social-media promotions, manage their own customer relationships, and place customer orders through RM Hub. Resellers must clearly identify the relevant Merchant and must not alter material product terms or make unauthorized medical, income, warranty, or performance claims.</p><h2>3. Customer and Order Duties</h2><p>Resellers must obtain customer authority before entering personal data, keep details accurate, explain price and shipping arrangements, protect customer information, remit required amounts, and communicate order status responsibly.</p><h2>4. Earnings and Risk</h2><p>Any margin depends on the Reseller’s lawful selling price, costs, fees, refunds, and customer arrangements. Resellers bear their own taxes, marketing costs, and business obligations.</p>$policy$,'2026-07-21','published'),
('commission','1.0','Commission Policy',$policy$<h2>1. Fees</h2><p>RM Hub may earn through Merchant subscriptions, transaction commissions, operation fees, or other fees clearly displayed before commitment. Current rates shown in the checkout, subscription, or campaign interface form part of the transaction.</p><h2>2. Calculation</h2><p>Percentage fees are calculated on the stated base and rounded to two decimal places. Shipping, taxes, discounts, refunds, and payment charges are included or excluded only as disclosed in the applicable screen.</p><h2>3. Changes and Records</h2><p>Rate changes apply prospectively after notice and do not alter completed transactions. Platform records are prima facie operational evidence, subject to correction of proven error.</p><h2>4. Taxes</h2><p>Each party is responsible for its own taxes, registrations, invoices, and statutory reporting.</p>$policy$,'2026-07-21','published'),
('refund','1.0','Refund and Dispute Policy',$policy$<h2>1. Merchant Responsibility</h2><p>The Merchant is primarily responsible for product defects, non-conformity, warranty, fulfillment, lawful cancellation, replacement, and refund obligations. Platform terms do not waive mandatory consumer rights.</p><h2>2. Reporting</h2><p>A claimant should report a dispute promptly with order number, description, communications, photos, proof of payment, and requested resolution. Parties must preserve the item and evidence where reasonable.</p><h2>3. Resolution</h2><p>RM Hub may facilitate communication, freeze a pending platform-controlled amount, request evidence, record an outcome, or refer parties to DTI, the courts, payment providers, or other authorities. RM Hub does not guarantee recovery where funds or delivery are outside its control.</p><h2>4. Exclusions</h2><p>Change-of-mind requests may be subject to disclosed Merchant terms, but defective, unsafe, misdescribed, counterfeit, or legally non-compliant goods remain subject to applicable law.</p>$policy$,'2026-07-21','published'),
('cookie','1.0','Cookie Policy',$policy$<h2>1. Technologies</h2><p>RM Hub may use essential cookies, local storage, and similar technologies for authentication, session continuity, security, preferences, carts, and service operation.</p><h2>2. Optional Analytics</h2><p>Non-essential analytics or marketing technologies should be activated only with appropriate notice and consent where required. Users may manage browser controls, although disabling essential storage may prevent sign-in or cart functions.</p><h2>3. Duration</h2><p>Session technologies expire when appropriate; persistent items remain only for their stated operational or consented purpose.</p>$policy$,'2026-07-21','published'),
('acceptable_use','1.0','Acceptable Use Policy',$policy$<h2>1. Prohibited Conduct</h2><p>Users must not list illegal, stolen, counterfeit, unsafe, recalled, regulated without authorization, or infringing goods; misrepresent identity, stock, price, reviews, discounts, income, warranties, or product qualities; manipulate transactions; evade fees; harvest data; share another person’s contact data unlawfully; upload malware; probe security; automate abusive access; harass users; or use RM Hub for fraud, laundering, or unlawful schemes.</p><h2>2. Enforcement</h2><p>RM Hub may remove content, limit features, preserve records, investigate, warn, suspend, terminate, and report conduct to affected parties or authorities, proportionate to risk and law.</p>$policy$,'2026-07-21','published'),
('termination','1.0','Account Suspension and Termination Policy',$policy$<h2>1. Grounds</h2><p>Access may be restricted for failed verification, expired subscriptions, unpaid fees, material breach, repeated complaints, fraud indicators, illegal or unsafe products, security threats, data misuse, government request, insolvency risk, or conduct harmful to users or RM Hub.</p><h2>2. Process</h2><p>Where practicable and lawful, RM Hub will give notice, the reason, and an opportunity to respond. Immediate restriction may apply to urgent fraud, safety, security, legal, or evidence-preservation concerns.</p><h2>3. Effects and Appeal</h2><p>Suspension may block listings, orders, payouts, or administration. Termination does not erase accrued liabilities or records required for disputes and law. Appeals must include supporting evidence and may be sent to support@tindahub.ph.</p>$policy$,'2026-07-21','published')
on conflict(policy_type,version) do nothing;
