import { useState } from 'react'
import { Loader2, X } from 'lucide-react'
import toast from 'react-hot-toast'
import { supabase } from '../../lib/supabase'
import { useAuth } from '../../contexts/AuthContext'

export default function OrderCaseModal({ order, open, onClose, onSaved }) {
  const {user}=useAuth()
  const [type,setType]=useState('cancellation'),[reason,setReason]=useState(''),[evidence,setEvidence]=useState(null),[saving,setSaving]=useState(false)
  if(!open||!order)return null
  const submit=async e=>{e.preventDefault();if(reason.trim().length<10)return toast.error('Provide at least 10 characters explaining the request.');if(type!=='cancellation'&&!evidence)return toast.error('Upload evidence for this request.');setSaving(true);let evidencePath=null;if(evidence){const ext=evidence.name.split('.').pop()?.toLowerCase()||'jpg';evidencePath=`${user.id}/${order.id}/${Date.now()}.${ext}`;const upload=await supabase.storage.from('order-case-evidence').upload(evidencePath,evidence,{contentType:evidence.type,upsert:false});if(upload.error){setSaving(false);return toast.error(upload.error.message)}}const{error}=await supabase.rpc('open_order_case',{p_order_id:order.id,p_case_type:type,p_reason:reason.trim(),p_evidence_url:evidencePath});setSaving(false);if(error)return toast.error(error.message.includes('one_open_case')?'This order already has an open case.':error.message);toast.success('Your request was submitted for review.');setReason('');setEvidence(null);onSaved?.();onClose()}
  return <div className="fixed inset-0 z-[90] grid place-items-center bg-ink/60 p-4 backdrop-blur-sm"><form onSubmit={submit} className="card max-h-[92vh] w-full max-w-lg overflow-y-auto p-6"><div className="flex items-center justify-between"><div><h2 className="font-display text-xl font-bold">Request help with order</h2><p className="text-xs text-ink/45">{order.order_number}</p></div><button type="button" onClick={onClose} className="rounded-lg p-2 hover:bg-cream"><X size={18}/></button></div><label className="mt-5 block text-sm font-semibold text-ink/70">Request type<select value={type} onChange={e=>setType(e.target.value)} className="input-field mt-1"><option value="cancellation">Cancellation</option><option value="dispute">Order dispute</option><option value="return">Return</option><option value="replacement">Replacement</option><option value="refund">Refund</option></select></label><label className="mt-4 block text-sm font-semibold text-ink/70">Reason<textarea required minLength="10" maxLength="1000" rows="5" value={reason} onChange={e=>setReason(e.target.value)} className="input-field mt-1 resize-none" placeholder="Describe what happened and your requested resolution."/></label><label className="mt-4 block text-sm font-semibold text-ink/70">Evidence {type==='cancellation'?'(optional)':'(required)'}<input required={type!=='cancellation'} type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e=>setEvidence(e.target.files?.[0]||null)} className="input-field mt-1"/><span className="mt-1 block text-[11px] font-normal text-ink/45">Photo, screenshot, receipt, or PDF · maximum 8 MB</span></label><p className="mt-3 rounded-xl bg-mango-100/60 p-3 text-xs leading-5 text-ink/55">Opening a dispute pauses automatic completion while Admin reviews the case. Keep photos, receipts, and conversations as evidence.</p><button disabled={saving} className="btn-primary mt-5 flex w-full items-center justify-center gap-2">{saving&&<Loader2 size={16} className="animate-spin"/>}{saving?'Submitting...':'Submit request'}</button></form></div>
}
