// Keyword lists include English, Tagalog/Filipino, and common Bisaya/
// Cebuano synonyms per topic — this matcher is a fixed keyword lookup
// (no real language understanding), so "any language" isn't actually
// achievable here; broadening keyword coverage is the honest ceiling
// for accuracy without AI. True any-language understanding needs the
// Groq-backed path in JomBits.jsx (see ask()) — its system prompt
// explicitly instructs the model to reply in whatever language the
// question was asked in.

const shared = [
  { id: 'register', keywords: ['register','registration','sign up','signup','create account','join','magparehistro','pagpaparehistro','paano gumawa ng account','paano sumali','paano mag sign up'], title: 'Create a JOM HUB account', route: '/signup', actionLabel: 'Register now', answer: 'Select Register now, verify your Gmail with the 6-digit OTP, choose Reseller or Merchant, and complete the required account details.' },
  { id: 'schedule', keywords: ['schedule','appointment','calendar','training','orientation','book date','iskedyul','oras ng training','kailan ang training','magpa schedule'], title: 'Schedule registration or training', route: '/#registration-calendar', actionLabel: 'Choose a schedule', answer: 'Select Choose a schedule to open the registration calendar. Pick an available date and time, enter your contact details, and submit the request for Admin confirmation.' },
  { id: 'information', keywords: ['information','details','learn more','what is jom hub','about jom hub','benefits','ano ang jom hub','impormasyon','mga benepisyo','paano gumagana ang jom hub'], title: 'JOM HUB information', route: '/#benefits', actionLabel: 'View system information', answer: 'JOM HUB connects approved Merchants and Resellers through organized products, customers, orders, wallet payments, delivery tracking, reports, notifications, and protected case handling.' },
  { id: 'security', keywords: ['otp','password','security','safe','scam','reference','seguridad','ligtas','iwas scam','huwag ibigay ang otp'], title: 'Account security', answer: 'Keep your email OTP, password, bank OTP, and payment codes private. Use a unique payment reference for every request and keep all order and payment evidence inside JOM HUB.' },
  { id: 'address', keywords: ['address','delivery address','pickup address','tirahan','address ng bahay','saan kukunin ang produkto','pickup address ko'], title: 'Account address', answer: 'Open Update Account or the Address page and save a complete address. JOM HUB requires complete location details before protected ordering and fulfillment actions are available.' },
  { id: 'case', keywords: ['cancel','cancellation','dispute','return','replacement','refund','problem','kanselahin','ikansela','reklamo','isyu','problema','palitan ang produkto','sirang produkto','pabalik ng pera'], title: 'Order cases', answer: 'Open the affected order, select Request Cancellation / Help, choose the correct case type, explain the issue, and attach evidence when required. An open case pauses automatic completion while it is reviewed.' },
  { id: 'notification', keywords: ['notification','alert','bell','abiso','notipikasyon','bell icon','paalala'], title: 'Notifications', answer: 'Use the bell in the workspace header to review account-specific order, wallet, subscription, and case updates.' },
  { id: 'guide', keywords: ['guide','walkthrough','tutorial','how to use','gabay','turo','paano gamitin ang system'], title: 'Page guide', answer: 'Select the guide icon beside the notification bell. It highlights the controls on your current page and explains each action step by step.' },
  { id: 'next-action', keywords: ['next action','what next','what should i do','priority','setup checklist','progress','susunod na gagawin','ano ang gagawin ko','checklist ko'], title: 'Setup checklist and Next Action', answer: 'Open your dashboard to see the five-step setup checklist and Recommended Next Action card. Each incomplete step links directly to the page where you can finish it.' },
  { id: 'receipt', keywords: ['receipt','print receipt','transaction record','proof of transaction','resibo','patunay ng bayad','print ng resibo'], title: 'Printable receipts', answer: 'Open the related order or Wallet request and select Print receipt. JOM HUB provides printable records for orders, top-ups, and withdrawals; always compare them with the official external payment record.' }
  ,{ id: 'mobile-navigation', keywords: ['mobile menu','bottom navigation','phone navigation','mobile navigation','menu sa telepono','navigation sa cellphone'], title: 'Mobile workspace navigation', answer: 'On your phone, use the bottom bar for Home, Products, Orders, Wallet, and Account. The full side menu remains available for customers, reports, campaigns, messages, and other tools.' }
  ,{ id: 'order-timeline', keywords: ['order timeline','order progress','order status steps','progreso ng order','status ng aking order','anong status ng order'], title: 'Visual order timeline', answer: 'Each order shows Confirmed, Processing, Shipped, and Completed. The label under each step identifies whether the Merchant, Reseller, or system is responsible for the next action.' }
]

const roleKnowledge = {
  reseller: [
    { id: 'start', keywords: ['start','begin','activate','approval','onboarding','paano magsimula','paano ma approve ang account ko','aktibo na ba ako'], title: 'Reseller activation', route: '/reseller/account', answer: 'Complete your profile and address to enter your dashboard right away. You can browse it immediately, but placing orders and adding customers stays locked until Admin approves both your ID verification (Verify Your Identity) and an initial wallet top-up, which you can submit anytime from Wallet.' },
    { id: 'customer', keywords: ['customer','client','buyer','kliyente','mamimili','customer ko','paano magdagdag ng customer'], title: 'Customers', route: '/reseller/customers', answer: 'Open Customers, add the customer with permission, and verify the name, phone, and complete delivery address before assigning products.' },
    { id: 'product', keywords: ['product','catalog','stock','buy','produkto','presyo ng bili','saan bibili ng produkto'], title: 'Products and buying price', route: '/catalog', answer: 'Browse approved products in the Catalog. Your Reseller buying price and available quantity are shown before you add an item to the cart.' },
    { id: 'storefront', keywords: ['storefront','store link','my product list','customer page','facebook','viber','whatsapp','how to buy','sariling tindahan','link ng tindahan ko','paano magbenta sa fb'], title: 'Reseller customer store', route: '/reseller/products', answer: 'Open a Merchant product and select Get for My Product List. Then open My Product List to set your store name, profile and cover photos, introduction, and optional Facebook, phone, Viber, or WhatsApp channels. Only products you selected appear on your unique customer link. Customers use How to Buy and cannot access the main system navigation from that store page.' },
    { id: 'profit', keywords: ['profit','income','earn','earning','sell price','selling price','margin','bulk','piece','kita','tubo','magkano ang kikitain ko','presyo ng benta'], title: 'Reseller earnings', route: '/cart', answer: 'Set your customer selling price in the product or cart view. Estimated profit is customer total minus your buying subtotal and the capped 1% system fee (minimum ₱3, maximum ₱50), before delivery, marketing, returns, and taxes.' },
    { id: 'order', keywords: ['order','checkout','cart','place order','pag order','paano mag order','pag checkout','magbayad ng order'], title: 'Place an order', route: '/cart', answer: 'Assign a saved customer, review quantity and selling price, wait for secure server price verification, then confirm checkout. The JOM HUB wallet pays the product subtotal plus the Reseller system fee; shipping is handled separately when shown.' },
    { id: 'delivery', keywords: ['delivery','shipping','shipping fee','shipped','tracking','receive','decline','padala','paghahatid','bayad sa shipping','tracking number','natanggap ko na'], title: 'Track delivery', route: '/reseller/orders', answer: 'After packaging, review the Merchant’s actual shipping fee in Orders. Accept it to allow dispatch, or decline it with a required note if you will not take the product. Confirm Delivery only after the items are actually received and checked.' },
    { id: 'wallet', keywords: ['wallet','balance','topup','top-up','cash in','pera','balanse','magdeposito','magcash in','paano magcash in'], title: 'Reseller wallet', route: '/reseller/wallet', answer: 'Use Wallet to submit a top-up with a unique reference and proof, review your ledger, or request a withdrawal. Funds become usable only after Admin approval.' },
    { id: 'withdraw', keywords: ['withdraw','withdrawal','bank','payout','kunin ang pera','magwithdraw','ilipat sa bangko','paano kumuha ng kita'], title: 'Withdraw funds', route: '/reseller/wallet', answer: 'Save the correct payout account, wait 24 hours after changing it, then request at least ₱500. The daily limit is ₱100,000. Admin will schedule and record the transfer reference and proof.' },
    { id: 'report', keywords: ['report','sales report','inventory report','history','excel','duration','date range','ulat','benta report','ulat ng benta'], title: 'Reseller reports', route: '/reseller/reports/sales', answer: 'Choose a duration or custom dates, select Apply Period, review the loaded period and totals, then download Excel. The workbook contains only the applied period. Customer income is realized only after you record the customer payment as Paid.' }
  ],
  merchant: [
    { id: 'start', keywords: ['start','begin','activate','approval','onboarding','permit','paano magsimula bilang merchant','permit ko','aktibo na ba ang account ko'], title: 'Merchant activation', route: '/merchant/account', answer: 'Complete your business profile and pickup address to enter your dashboard right away. Signing up also grants a free 6-month subscription automatically. Posting products stays locked until Admin approves your business permit -- upload it from there. If your permit is still under review and you need to operate sooner, you can send Admin a follow-up request for temporary access from your dashboard.' },
    { id: 'subscription', keywords: ['subscription','renew','expiry','expired','fee','subscription ko','paano mag renew','bayad sa subscription','nag expire na'], title: 'Merchant subscription', route: '/choose-subscription', answer: 'Every Merchant gets a free 6-month subscription automatically at signup. Once it expires, your whole dashboard locks -- you cannot browse, post products, or receive orders until you renew from the subscription page. Admin can also manually extend or grant a subscription.' },
    { id: 'product', keywords: ['product','upload','listing','stock','price','wholesale','produkto','paglagay ng produkto','magpost ng produkto','presyo ng produkto'], title: 'Product listing', route: '/merchant/products/new', answer: 'Create a product with truthful details, a real image, stock, retail and wholesale prices, packed measurements, and handling needs. Prohibited, illegal, counterfeit, unsafe, or misleading products cannot be posted.' },
    { id: 'profit', keywords: ['profit','income','earn','earning','proceeds','margin','fee','kita ng merchant','tubo','magkano ang kikitain'], title: 'Merchant proceeds', route: '/merchant/reports/sales', answer: 'Merchant proceeds are the completed product subtotal less the 3% completed-order platform fee. Your real profit must also subtract product cost, packaging, fulfillment, returns, and taxes.' },
    { id: 'order', keywords: ['order','customer order','processing','confirm','shipping fee','packaging','proseso ng order','kumpirmahin ang order','pag package'], title: 'Process an order', route: '/merchant/orders', answer: 'Move an accepted order to Processing, package the exact items, and submit the actual shipping fee. Dispatch remains locked until the Reseller accepts. If declined, review the required note and submit a revised fee when appropriate.' },
    { id: 'delivery', keywords: ['delivery','shipping','ship','tracking','courier','dispatch','ipadala ang order','pag padala','madeliver','ihatid','paano ihahatid','paano ko ihahatid'], title: 'Dispatch an order', route: '/merchant/orders', answer: 'Before marking an order Shipped, enter the courier, tracking number, pickup time, delivery estimate, actual fee, and dispatch proof. Payout is released only after protected completion.' },
    { id: 'wallet', keywords: ['wallet','balance','topup','top-up','pera ng merchant','balanse ko','payout'], title: 'Merchant wallet', route: '/merchant/wallet', answer: 'Use Wallet to review completed-order payouts, top-ups, withdrawals, and ledger entries. Always reconcile wallet activity with Sales and Ordered reports.' },
    { id: 'withdraw', keywords: ['withdraw','withdrawal','bank','payout','kunin ang bayad','magwithdraw','ilipat sa bangko'], title: 'Withdraw funds', route: '/merchant/wallet', answer: 'Save the correct payout account, wait 24 hours after changing it, then request at least ₱500 within the ₱100,000 daily limit. Admin schedules the payout and records proof after sending.' },
    { id: 'store', keywords: ['store hours','open store','close store','opening','closing','oras ng tindahan','bukas at sara ng tindahan'], title: 'Store availability', route: '/merchant/account', answer: 'Set optional opening and closing hours in Update Account. When automatic store hours are enabled, products become unavailable outside your schedule.' },
    { id: 'report', keywords: ['report','sales report','inventory report','history','excel','duration','date range','ulat ng benta','report ng merchant'], title: 'Merchant reports', route: '/merchant/reports/sales', answer: 'Choose a duration or custom dates, select Apply Period, review the loaded period and totals, then download Excel. Sales, orders, top-ups, and withdrawals use that period; Inventory is a live stock snapshot.' }
  ]
}

const normalize = (value = '') => value.toLowerCase().replace(/[^a-z0-9%₱\s-]/g, ' ').replace(/\s+/g, ' ').trim()

export function getJomBitsSuggestions(role, pathname = '') {
  if (pathname.includes('/orders')) return role === 'merchant' ? ['What should I do with this order?', 'How do I ship an order?', 'How do order cases work?', 'Where is the tracking number?'] : ['How do I track delivery?', 'When should I confirm delivery?', 'How do I request help?', 'How do I print a receipt?']
  if (pathname.includes('/wallet')) return ['How do top-ups work?', 'How do withdrawals work?', 'How do I print a receipt?', 'Why is my balance pending?']
  if (pathname.includes('/products')) return role === 'merchant' ? ['How do I add a product?', 'What products are prohibited?', 'How should I set prices?', 'How do quantity offers work?'] : ['How do I choose a product?', 'How is my profit calculated?', 'Can I buy one piece?', 'How does bulk pricing work?']
  return role === 'merchant'
    ? ['How do I add a product?', 'How is Merchant profit calculated?', 'How do I ship an order?', 'How do withdrawals work?']
    : ['How do I place an order?', 'How is my profit calculated?', 'How do I track delivery?', 'How do withdrawals work?']
}

export function answerJomBits(question, role, pathname = '') {
  const query = normalize(question)
  const entries = [...(roleKnowledge[role] || []), ...shared]
  if (!query) return { title: 'Ask JOM Bits', answer: 'Enter a question about your JOM HUB workspace.' }
  let best = null
  let score = 0
  for (const entry of entries) {
    const candidate = entry.keywords.reduce((total, keyword) => {
      const clean = normalize(keyword)
      return total + (query.includes(clean) ? clean.split(' ').length + 1 : 0)
    }, 0)
    if (candidate > score) { best = entry; score = candidate }
  }
  if (best) return { ...best, answer: `${best.answer}${best.route && pathname.startsWith(best.route) ? ' You are already on the relevant page.' : ''}` }
  return { title: 'JOM HUB questions only', answer: `I can only help with JOM HUB ${role === 'merchant' ? 'Merchant' : 'Reseller'} processes, registration, schedules, account features, orders, products, wallet activity, reports, and security. Try one of the suggested questions. / Tanong lang tungkol sa JOM HUB ang masasagot ko — subukan ang isa sa mga suggestion sa ibaba.` }
}
