// Keyword lists include English, Tagalog/Filipino, and common Bisaya/
// Cebuano synonyms per topic. Every entry also carries a Tagalog
// translation (title/answer/actionLabel + "Tl" suffix) alongside the
// English original — detectTagalog() below picks which one to return
// based on common Tagalog function words in the question, so the
// offline matcher answers in the same language it was asked in, not
// just recognizes it. This is still fixed-list translation, not real
// language understanding — Bisaya and other languages fall back to the
// English answer here (only Tagalog has a full translation pass);
// genuine any-language understanding needs the Groq-backed path in
// JomBits.jsx (see ask()) — its system prompt handles any language.

const shared = [
  { id: 'register', keywords: ['register','registration','sign up','signup','create account','join','magparehistro','pagpaparehistro','paano gumawa ng account','paano sumali','paano mag sign up'], title: 'Create a JOM HUB account', titleTl: 'Paggawa ng JOM HUB account', route: '/signup', actionLabel: 'Register now', actionLabelTl: 'Magrehistro ngayon', answer: 'Select Register now, verify your Gmail with the 6-digit OTP, choose Reseller or Merchant, and complete the required account details.', answerTl: 'Piliin ang Register now, i-verify ang iyong Gmail gamit ang 6-digit na OTP, piliin kung Reseller o Merchant, at kumpletuhin ang mga kailangang detalye ng account.' },
  { id: 'schedule', keywords: ['schedule','appointment','calendar','training','orientation','book date','iskedyul','oras ng training','kailan ang training','magpa schedule'], title: 'Schedule registration or training', titleTl: 'Pag-iskedyul ng registration o training', route: '/#registration-calendar', actionLabel: 'Choose a schedule', actionLabelTl: 'Pumili ng schedule', answer: 'Select Choose a schedule to open the registration calendar. Pick an available date and time, enter your contact details, and submit the request for Admin confirmation.', answerTl: 'Piliin ang Choose a schedule para buksan ang registration calendar. Pumili ng bukas na petsa at oras, ilagay ang iyong contact details, at isumite ang request para sa kumpirmasyon ng Admin.' },
  { id: 'information', keywords: ['information','details','learn more','what is jom hub','about jom hub','benefits','ano ang jom hub','impormasyon','mga benepisyo','paano gumagana ang jom hub'], title: 'JOM HUB information', titleTl: 'Impormasyon tungkol sa JOM HUB', route: '/#benefits', actionLabel: 'View system information', actionLabelTl: 'Tingnan ang impormasyon ng system', answer: 'JOM HUB connects approved Merchants and Resellers through organized products, customers, orders, wallet payments, delivery tracking, reports, notifications, and protected case handling.', answerTl: 'Ikinokonekta ng JOM HUB ang mga aprubadong Merchant at Reseller sa pamamagitan ng maayos na produkto, customer, order, wallet payment, delivery tracking, ulat, notipikasyon, at protektadong paghawak ng kaso.' },
  { id: 'security', keywords: ['otp','password','security','safe','scam','reference','seguridad','ligtas','iwas scam','huwag ibigay ang otp'], title: 'Account security', titleTl: 'Seguridad ng account', answer: 'Keep your email OTP, password, bank OTP, and payment codes private. Use a unique payment reference for every request and keep all order and payment evidence inside JOM HUB.', answerTl: 'Panatilihing pribado ang iyong email OTP, password, bank OTP, at payment codes. Gumamit ng natatanging payment reference sa bawat request at panatilihin ang lahat ng ebidensya ng order at bayad sa loob ng JOM HUB.' },
  { id: 'address', keywords: ['address','delivery address','pickup address','tirahan','address ng bahay','saan kukunin ang produkto','pickup address ko'], title: 'Account address', titleTl: 'Address ng account', answer: 'Open Update Account or the Address page and save a complete address. JOM HUB requires complete location details before protected ordering and fulfillment actions are available.', answerTl: 'Buksan ang Update Account o ang Address page at i-save ang kumpletong address. Kailangan ng JOM HUB ng kumpletong detalye ng lokasyon bago magamit ang mga protektadong aksyon sa pag-order at fulfillment.' },
  { id: 'case', keywords: ['cancel','cancellation','dispute','return','replacement','refund','problem','kanselahin','ikansela','reklamo','isyu','problema','palitan ang produkto','sirang produkto','pabalik ng pera'], title: 'Order cases', titleTl: 'Mga kaso ng order', answer: 'Open the affected order, select Request Cancellation / Help, choose the correct case type, explain the issue, and attach evidence when required. An open case pauses automatic completion while it is reviewed.', answerTl: 'Buksan ang apektadong order, piliin ang Request Cancellation / Help, piliin ang tamang uri ng kaso, ipaliwanag ang isyu, at maglagay ng ebidensya kung kinakailangan. Ang bukas na kaso ay pinapatigil muna ang automatic completion habang ito ay sinusuri.' },
  { id: 'notification', keywords: ['notification','alert','bell','abiso','notipikasyon','bell icon','paalala'], title: 'Notifications', titleTl: 'Mga notipikasyon', answer: 'Use the bell in the workspace header to review account-specific order, wallet, subscription, and case updates.', answerTl: 'Gamitin ang bell sa header ng workspace para tingnan ang mga update sa order, wallet, subscription, at kaso na partikular sa iyong account.' },
  { id: 'guide', keywords: ['guide','walkthrough','tutorial','how to use','gabay','turo','paano gamitin ang system'], title: 'Page guide', titleTl: 'Gabay sa page', answer: 'Select the guide icon beside the notification bell. It highlights the controls on your current page and explains each action step by step.', answerTl: 'Piliin ang guide icon sa tabi ng notification bell. Ito ay nagha-highlight ng mga control sa iyong kasalukuyang page at nagpapaliwanag ng bawat aksyon nang paisa-isa.' },
  { id: 'next-action', keywords: ['next action','what next','what should i do','priority','setup checklist','progress','susunod na gagawin','ano ang gagawin ko','checklist ko'], title: 'Setup checklist and Next Action', titleTl: 'Setup checklist at Next Action', answer: 'Open your dashboard to see the five-step setup checklist and Recommended Next Action card. Each incomplete step links directly to the page where you can finish it.', answerTl: 'Buksan ang iyong dashboard para makita ang five-step setup checklist at ang Recommended Next Action card. Ang bawat hindi pa tapos na hakbang ay direktang naka-link sa page kung saan mo ito matatapos.' },
  { id: 'receipt', keywords: ['receipt','print receipt','transaction record','proof of transaction','resibo','patunay ng bayad','print ng resibo'], title: 'Printable receipts', titleTl: 'Maaaring i-print na resibo', answer: 'Open the related order or Wallet request and select Print receipt. JOM HUB provides printable records for orders, top-ups, and withdrawals; always compare them with the official external payment record.', answerTl: 'Buksan ang kaugnay na order o Wallet request at piliin ang Print receipt. Nagbibigay ang JOM HUB ng maaaring i-print na rekord para sa mga order, top-up, at withdrawal; laging ikumpara ito sa opisyal na external payment record.' }
  ,{ id: 'mobile-navigation', keywords: ['mobile menu','bottom navigation','phone navigation','mobile navigation','menu sa telepono','navigation sa cellphone'], title: 'Mobile workspace navigation', titleTl: 'Navigation sa mobile workspace', answer: 'On your phone, use the bottom bar for Home, Products, Orders, Wallet, and Account. The full side menu remains available for customers, reports, campaigns, messages, and other tools.', answerTl: 'Sa iyong telepono, gamitin ang bottom bar para sa Home, Products, Orders, Wallet, at Account. Available pa rin ang buong side menu para sa customers, reports, campaigns, messages, at iba pang tools.' }
  ,{ id: 'order-timeline', keywords: ['order timeline','order progress','order status steps','progreso ng order','status ng aking order','anong status ng order'], title: 'Visual order timeline', titleTl: 'Visual na order timeline', answer: 'Each order shows Confirmed, Processing, Shipped, and Completed. The label under each step identifies whether the Merchant, Reseller, or system is responsible for the next action.', answerTl: 'Ipinapakita ng bawat order ang Confirmed, Processing, Shipped, at Completed. Ang label sa ilalim ng bawat hakbang ay nagsasabi kung ang Merchant, Reseller, o system ang responsable sa susunod na aksyon.' }
]

const roleKnowledge = {
  reseller: [
    { id: 'start', keywords: ['start','begin','activate','approval','onboarding','paano magsimula','paano ma approve ang account ko','aktibo na ba ako'], title: 'Reseller activation', titleTl: 'Pag-activate bilang Reseller', route: '/reseller/account', answer: 'Complete your profile and address to enter your dashboard right away. You can browse it immediately, but placing orders and adding customers stays locked until Admin approves both your ID verification (Verify Your Identity) and an initial wallet top-up, which you can submit anytime from Wallet.', answerTl: 'Kumpletuhin ang iyong profile at address para agad makapasok sa iyong dashboard. Puwede mo itong i-browse kaagad, pero naka-lock pa ang pag-order at pagdagdag ng customer hanggang aprubahan ng Admin ang iyong ID verification (Verify Your Identity) at unang wallet top-up, na puwede mong isumite anumang oras mula sa Wallet.' },
    { id: 'customer', keywords: ['customer','client','buyer','kliyente','mamimili','customer ko','paano magdagdag ng customer'], title: 'Customers', titleTl: 'Mga Customer', route: '/reseller/customers', answer: 'Open Customers, add the customer with permission, and verify the name, phone, and complete delivery address before assigning products.', answerTl: 'Buksan ang Customers, idagdag ang customer nang may pahintulot, at i-verify ang pangalan, numero ng telepono, at kumpletong delivery address bago mag-assign ng mga produkto.' },
    { id: 'product', keywords: ['product','catalog','stock','buy','produkto','presyo ng bili','saan bibili ng produkto'], title: 'Products and buying price', titleTl: 'Mga produkto at presyo ng pagbili', route: '/catalog', answer: 'Browse approved products in the Catalog. Your Reseller buying price and available quantity are shown before you add an item to the cart.', answerTl: 'I-browse ang mga aprubadong produkto sa Catalog. Ipinapakita ang iyong Reseller buying price at available na quantity bago ka magdagdag ng item sa cart.' },
    { id: 'storefront', keywords: ['storefront','store link','my product list','customer page','facebook','viber','whatsapp','how to buy','sariling tindahan','link ng tindahan ko','paano magbenta sa fb'], title: 'Reseller customer store', titleTl: 'Tindahan ng Reseller para sa customer', route: '/reseller/products', answer: 'Open a Merchant product and select Get for My Product List. Then open My Product List to set your store name, profile and cover photos, introduction, and optional Facebook, phone, Viber, or WhatsApp channels. Only products you selected appear on your unique customer link. Customers use How to Buy and cannot access the main system navigation from that store page.', answerTl: 'Buksan ang produkto ng Merchant at piliin ang Get for My Product List. Pagkatapos, buksan ang My Product List para i-set ang pangalan ng tindahan, profile at cover photo, introduction, at opsyonal na Facebook, telepono, Viber, o WhatsApp channels. Ang mga produkto lang na napili mo ang lalabas sa iyong natatanging customer link. Gagamitin ng mga customer ang How to Buy at hindi nila maa-access ang pangunahing system navigation mula sa store page na iyon.' },
    { id: 'profit', keywords: ['profit','income','earn','earning','sell price','selling price','margin','bulk','piece','kita','tubo','magkano ang kikitain ko','presyo ng benta'], title: 'Reseller earnings', titleTl: 'Kita ng Reseller', route: '/cart', answer: 'Set your customer selling price in the product or cart view. Estimated profit is customer total minus your buying subtotal and the capped 1% system fee (minimum ₱3, maximum ₱50), before delivery, marketing, returns, and taxes.', answerTl: 'I-set ang iyong customer selling price sa product o cart view. Ang estimated profit ay ang kabuuang bayad ng customer minus ang iyong buying subtotal at ang naka-cap na 1% system fee (minimum ₱3, maximum ₱50), bago pa ang delivery, marketing, returns, at buwis.' },
    { id: 'order', keywords: ['order','checkout','cart','place order','pag order','paano mag order','pag checkout','magbayad ng order'], title: 'Place an order', titleTl: 'Pag-order', route: '/cart', answer: 'Assign a saved customer, review quantity and selling price, wait for secure server price verification, then confirm checkout. The JOM HUB wallet pays the product subtotal plus the Reseller system fee; shipping is handled separately when shown.', answerTl: 'Mag-assign ng naka-save na customer, suriin ang quantity at selling price, hintayin ang secure server price verification, tapos kumpirmahin ang checkout. Ang JOM HUB wallet ang magbabayad ng product subtotal kasama ang Reseller system fee; hiwalay na hinahawakan ang shipping kapag ipinakita ito.' },
    { id: 'delivery', keywords: ['delivery','shipping','shipping fee','shipped','tracking','receive','decline','padala','paghahatid','bayad sa shipping','tracking number','natanggap ko na'], title: 'Track delivery', titleTl: 'Pagsubaybay sa delivery', route: '/reseller/orders', answer: 'After packaging, review the Merchant’s actual shipping fee in Orders. Accept it to allow dispatch, or decline it with a required note if you will not take the product. Confirm Delivery only after the items are actually received and checked.', answerTl: 'Pagkatapos ng packaging, suriin ang aktwal na shipping fee ng Merchant sa Orders. Tanggapin ito para payagan ang dispatch, o i-decline ito na may kasamang required na note kung hindi mo tatanggapin ang produkto. I-confirm ang Delivery lamang pagkatapos na aktwal na natanggap at nasuri ang mga item.' },
    { id: 'wallet', keywords: ['wallet','balance','topup','top-up','cash in','pera','balanse','magdeposito','magcash in','paano magcash in'], title: 'Reseller wallet', titleTl: 'Wallet ng Reseller', route: '/reseller/wallet', answer: 'Use Wallet to submit a top-up with a unique reference and proof, review your ledger, or request a withdrawal. Funds become usable only after Admin approval.', answerTl: 'Gamitin ang Wallet para magsumite ng top-up na may natatanging reference at proof, suriin ang iyong ledger, o mag-request ng withdrawal. Magagamit lang ang pondo pagkatapos aprubahan ng Admin.' },
    { id: 'withdraw', keywords: ['withdraw','withdrawal','bank','payout','kunin ang pera','magwithdraw','ilipat sa bangko','paano kumuha ng kita'], title: 'Withdraw funds', titleTl: 'Pag-withdraw ng pondo', route: '/reseller/wallet', answer: 'Save the correct payout account, wait 24 hours after changing it, then request at least ₱500. The daily limit is ₱100,000. Admin will schedule and record the transfer reference and proof.', answerTl: 'I-save ang tamang payout account, maghintay ng 24 oras pagkatapos itong palitan, tapos mag-request ng hindi bababa sa ₱500. Ang daily limit ay ₱100,000. Ise-schedule at ire-record ng Admin ang transfer reference at proof.' },
    { id: 'report', keywords: ['report','sales report','inventory report','history','excel','duration','date range','ulat','benta report','ulat ng benta'], title: 'Reseller reports', titleTl: 'Ulat ng Reseller', route: '/reseller/reports/sales', answer: 'Choose a duration or custom dates, select Apply Period, review the loaded period and totals, then download Excel. The workbook contains only the applied period. Customer income is realized only after you record the customer payment as Paid.', answerTl: 'Pumili ng duration o custom na petsa, piliin ang Apply Period, suriin ang na-load na period at totals, tapos i-download ang Excel. Ang workbook ay naglalaman lamang ng inilapat na period. Ang income mula sa customer ay ma-rerealize lamang pagkatapos mong i-record ang bayad ng customer bilang Paid.' }
  ],
  merchant: [
    { id: 'start', keywords: ['start','begin','activate','approval','onboarding','permit','paano magsimula bilang merchant','permit ko','aktibo na ba ang account ko'], title: 'Merchant activation', titleTl: 'Pag-activate bilang Merchant', route: '/merchant/account', answer: 'Complete your business profile and pickup address to enter your dashboard right away. Signing up also grants a free 6-month subscription automatically. Posting products stays locked until Admin approves your business permit -- upload it from there. If your permit is still under review and you need to operate sooner, you can send Admin a follow-up request for temporary access from your dashboard.', answerTl: 'Kumpletuhin ang iyong business profile at pickup address para agad makapasok sa iyong dashboard. Ang pagsali ay awtomatikong nagbibigay din ng libreng 6-buwang subscription. Naka-lock ang pag-post ng produkto hanggang aprubahan ng Admin ang iyong business permit -- i-upload ito mula doon. Kung nasa review pa ang permit mo at kailangan mong mag-operate nang mas maaga, puwede kang magpadala ng follow-up request sa Admin para sa pansamantalang access mula sa iyong dashboard.' },
    { id: 'subscription', keywords: ['subscription','renew','expiry','expired','fee','subscription ko','paano mag renew','bayad sa subscription','nag expire na'], title: 'Merchant subscription', titleTl: 'Subscription ng Merchant', route: '/choose-subscription', answer: 'Every Merchant gets a free 6-month subscription automatically at signup. Once it expires, your whole dashboard locks -- you cannot browse, post products, or receive orders until you renew from the subscription page. Admin can also manually extend or grant a subscription.', answerTl: 'Bawat Merchant ay awtomatikong nakakakuha ng libreng 6-buwang subscription sa pag-signup. Kapag nag-expire ito, naka-lock ang buong dashboard mo -- hindi ka makaka-browse, makaka-post ng produkto, o makakatanggap ng order hanggang i-renew mo ito mula sa subscription page. Puwede ring manu-manong pahabain o bigyan ng subscription ng Admin.' },
    { id: 'product', keywords: ['product','upload','listing','stock','price','wholesale','produkto','paglagay ng produkto','magpost ng produkto','presyo ng produkto'], title: 'Product listing', titleTl: 'Paglista ng produkto', route: '/merchant/products/new', answer: 'Create a product with truthful details, a real image, stock, retail and wholesale prices, packed measurements, and handling needs. Prohibited, illegal, counterfeit, unsafe, or misleading products cannot be posted.', answerTl: 'Gumawa ng produkto na may totoong detalye, totoong larawan, stock, retail at wholesale prices, packed measurements, at handling needs. Hindi puwedeng i-post ang mga ipinagbabawal, iligal, peke, delikado, o mapanlinlang na produkto.' },
    { id: 'profit', keywords: ['profit','income','earn','earning','proceeds','margin','fee','kita ng merchant','tubo','magkano ang kikitain'], title: 'Merchant proceeds', titleTl: 'Kita ng Merchant', route: '/merchant/reports/sales', answer: 'Merchant proceeds are the completed product subtotal less the 3% completed-order platform fee. Your real profit must also subtract product cost, packaging, fulfillment, returns, and taxes.', answerTl: 'Ang Merchant proceeds ay ang completed product subtotal minus ang 3% completed-order platform fee. Ang iyong tunay na kita ay dapat ding bawasan ng product cost, packaging, fulfillment, returns, at buwis.' },
    { id: 'order', keywords: ['order','customer order','processing','confirm','shipping fee','packaging','proseso ng order','kumpirmahin ang order','pag package'], title: 'Process an order', titleTl: 'Pagproseso ng order', route: '/merchant/orders', answer: 'Move an accepted order to Processing, package the exact items, and submit the actual shipping fee. Dispatch remains locked until the Reseller accepts. If declined, review the required note and submit a revised fee when appropriate.', answerTl: 'Ilipat ang tinanggap na order sa Processing, i-package ang eksaktong item, at isumite ang aktwal na shipping fee. Naka-lock ang dispatch hanggang tanggapin ito ng Reseller. Kung na-decline, suriin ang required na note at magsumite ng binagong fee kung kinakailangan.' },
    { id: 'delivery', keywords: ['delivery','shipping','ship','tracking','courier','dispatch','ipadala ang order','pag padala','madeliver','ihatid','paano ihahatid','paano ko ihahatid'], title: 'Dispatch an order', titleTl: 'Pagpapadala ng order', route: '/merchant/orders', answer: 'Before marking an order Shipped, enter the courier, tracking number, pickup time, delivery estimate, actual fee, and dispatch proof. Payout is released only after protected completion.', answerTl: 'Bago markahan ang order bilang Shipped, ilagay ang courier, tracking number, pickup time, delivery estimate, aktwal na fee, at dispatch proof. Ipapalabas lang ang payout pagkatapos ng protected completion.' },
    { id: 'wallet', keywords: ['wallet','balance','topup','top-up','pera ng merchant','balanse ko','payout'], title: 'Merchant wallet', titleTl: 'Wallet ng Merchant', route: '/merchant/wallet', answer: 'Use Wallet to review completed-order payouts, top-ups, withdrawals, and ledger entries. Always reconcile wallet activity with Sales and Ordered reports.', answerTl: 'Gamitin ang Wallet para suriin ang mga payout ng completed order, top-up, withdrawal, at ledger entries. Laging i-reconcile ang wallet activity sa Sales at Ordered reports.' },
    { id: 'withdraw', keywords: ['withdraw','withdrawal','bank','payout','kunin ang bayad','magwithdraw','ilipat sa bangko'], title: 'Withdraw funds', titleTl: 'Pag-withdraw ng pondo', route: '/merchant/wallet', answer: 'Save the correct payout account, wait 24 hours after changing it, then request at least ₱500 within the ₱100,000 daily limit. Admin schedules the payout and records proof after sending.', answerTl: 'I-save ang tamang payout account, maghintay ng 24 oras pagkatapos itong palitan, tapos mag-request ng hindi bababa sa ₱500 sa loob ng ₱100,000 daily limit. Ise-schedule ng Admin ang payout at ire-record ang proof pagkatapos ipadala.' },
    { id: 'store', keywords: ['store hours','open store','close store','opening','closing','oras ng tindahan','bukas at sara ng tindahan'], title: 'Store availability', titleTl: 'Availability ng tindahan', route: '/merchant/account', answer: 'Set optional opening and closing hours in Update Account. When automatic store hours are enabled, products become unavailable outside your schedule.', answerTl: 'I-set ang opsyonal na oras ng pagbukas at pagsara sa Update Account. Kapag naka-enable ang automatic store hours, hindi available ang mga produkto sa labas ng iyong schedule.' },
    { id: 'report', keywords: ['report','sales report','inventory report','history','excel','duration','date range','ulat ng benta','report ng merchant'], title: 'Merchant reports', titleTl: 'Ulat ng Merchant', route: '/merchant/reports/sales', answer: 'Choose a duration or custom dates, select Apply Period, review the loaded period and totals, then download Excel. Sales, orders, top-ups, and withdrawals use that period; Inventory is a live stock snapshot.', answerTl: 'Pumili ng duration o custom na petsa, piliin ang Apply Period, suriin ang na-load na period at totals, tapos i-download ang Excel. Gumagamit ng period na iyon ang Sales, orders, top-up, at withdrawal; ang Inventory ay live na stock snapshot.' }
  ]
}

const normalize = (value = '') => value.toLowerCase().replace(/[^a-z0-9%₱\s-]/g, ' ').replace(/\s+/g, ' ').trim()

// Common short Tagalog function words — characteristic enough that their
// presence reliably signals a Tagalog/Taglish question, without needing
// real language detection. Bisaya and other languages aren't covered
// here (still answer in English) — see the file header note.
const TAGALOG_MARKERS = new Set(['ang','mga','ko','mo','po','ba','paano','saan','kailan','bakit','sino','gaano','kung','wala','walang','meron','mayroon','gusto','pwede','puwede','hindi','lang','din','rin','yun','yung','ito','iyon','akin','kanya','niya','nila','siya','ako','kami','tayo','natin','atin','dapat','kelan','alin','ilan','magkano','anong','saang','nung','kasi','kayo','namin'])

function isTagalogQuestion(question) {
  const words = normalize(question).split(' ').filter(Boolean)
  return words.some((word) => TAGALOG_MARKERS.has(word))
}

export function getJomBitsSuggestions(role, pathname = '') {
  if (pathname.includes('/orders')) return role === 'merchant' ? ['What should I do with this order?', 'How do I ship an order?', 'How do order cases work?', 'Where is the tracking number?'] : ['How do I track delivery?', 'When should I confirm delivery?', 'How do I request help?', 'How do I print a receipt?']
  if (pathname.includes('/wallet')) return ['How do top-ups work?', 'How do withdrawals work?', 'How do I print a receipt?', 'Why is my balance pending?']
  if (pathname.includes('/products')) return role === 'merchant' ? ['How do I add a product?', 'What products are prohibited?', 'How should I set prices?', 'How do quantity offers work?'] : ['How do I choose a product?', 'How is my profit calculated?', 'Can I buy one piece?', 'How does bulk pricing work?']
  return role === 'merchant'
    ? ['How do I add a product?', 'How is Merchant profit calculated?', 'How do I ship an order?', 'How do withdrawals work?']
    : ['How do I place an order?', 'How is my profit calculated?', 'How do I track delivery?', 'How do withdrawals work?']
}

export function answerJomBits(question, role, pathname = '') {
  const query = normalize(question)
  const tagalog = isTagalogQuestion(question)
  const entries = [...(roleKnowledge[role] || []), ...shared]
  if (!query) return { title: 'Ask JOM Bits', answer: 'Enter a question about your JOM HUB workspace.' }
  let best = null
  let score = 0
  for (const entry of entries) {
    const candidate = entry.keywords.reduce((total, keyword) => {
      const clean = normalize(keyword)
      return total + (query.includes(clean) ? clean.split(' ').length + 1 : 0)
    }, 0)
    if (candidate > score) { best = entry; score = candidate }
  }
  if (best) {
    const title = tagalog && best.titleTl ? best.titleTl : best.title
    const actionLabel = tagalog && best.actionLabelTl ? best.actionLabelTl : best.actionLabel
    let answer = tagalog && best.answerTl ? best.answerTl : best.answer
    if (best.route && pathname.startsWith(best.route)) answer += tagalog ? ' Nasa kaugnay na page ka na.' : ' You are already on the relevant page.'
    return { ...best, title, actionLabel, answer }
  }
  const roleLabel = role === 'merchant' ? 'Merchant' : 'Reseller'
  return tagalog
    ? { title: 'JOM HUB na tanong lang', answer: `Makakatulong lang ako sa mga proseso ng JOM HUB para sa ${roleLabel}, pagpaparehistro, iskedyul, mga feature ng account, order, produkto, wallet activity, ulat, at seguridad. Subukan ang isa sa mga suggested na tanong.` }
    : { title: 'JOM HUB questions only', answer: `I can only help with JOM HUB ${roleLabel} processes, registration, schedules, account features, orders, products, wallet activity, reports, and security. Try one of the suggested questions.` }
}
