// Category ids from the live `categories` table (Electronics & Gadgets,
// Fashion & Apparel, Grocery & Food, Home & Living) — this file already
// targets one specific database (fixed SKUs, fixed image paths), so
// hardcoding these alongside everything else here is consistent with
// the rest of the file, not a new assumption.
const CATEGORY = {
  electronics: 'f387cca1-b625-4dc4-9618-e03d9706a977',
  fashion: 'b6f988c5-4cb5-4d71-9e84-594ac99b4983',
  grocery: '923f9b66-1850-4e50-b255-d76b8ac35587',
  home: 'e0e74645-7975-4ed8-88b3-e2af404b2518',
}

export const SAMPLE_PRODUCTS = [
  { sku: 'JOM-SAMPLE-RICE-5KG', category_id: CATEGORY.grocery, name: 'Premium Dinorado Rice 5kg', description: 'Locally sourced premium Dinorado rice packed in a sealed 5kg bag. Ideal for households, small eateries, and reseller bundles.', price: 420, wholesale_price: 345, suggested_retail_price: 420, stock_quantity: 80, min_order_qty: 2, discount_tiers: [{ min_qty: 10, discount_percent: 4, price: 331.2 }, { min_qty: 25, discount_percent: 7, price: 320.85 }], packed_weight_kg: 5.1, packed_length_cm: 42, packed_width_cm: 28, packed_height_cm: 10, product_type: 'Packaged rice', fragile: false, keep_upright: false, motorcycle_safe: true, images: ['/sample-products/dinorado-rice-photo.png'], is_active: true },
  { sku: 'JOM-SAMPLE-COFFEE-10', category_id: CATEGORY.grocery, name: 'Barako Drip Coffee 10-Pack', description: 'Aromatic Filipino Barako coffee in convenient individual drip bags. A gift-ready and easy-to-resell local coffee pack.', price: 299, wholesale_price: 220, suggested_retail_price: 299, stock_quantity: 120, min_order_qty: 3, discount_tiers: [{ min_qty: 12, discount_percent: 5, price: 209 }, { min_qty: 30, discount_percent: 9, price: 200.2 }], packed_weight_kg: 0.28, packed_length_cm: 22, packed_width_cm: 16, packed_height_cm: 8, product_type: 'Packaged coffee', fragile: false, keep_upright: false, motorcycle_safe: true, images: ['/sample-products/barako-coffee-photo.png'], is_active: true },
  { sku: 'JOM-SAMPLE-CHIPS-12', category_id: CATEGORY.grocery, name: 'Sweet Banana Chips 12-Pack', description: 'Crispy sweet banana chips in twelve sealed snack packs. Ready for sari-sari stores, school snacks, and online reselling.', price: 360, wholesale_price: 270, suggested_retail_price: 360, stock_quantity: 95, min_order_qty: 2, discount_tiers: [{ min_qty: 10, discount_percent: 5, price: 256.5 }, { min_qty: 20, discount_percent: 8, price: 248.4 }], packed_weight_kg: 1.1, packed_length_cm: 32, packed_width_cm: 24, packed_height_cm: 18, product_type: 'Packaged snack', fragile: true, keep_upright: false, motorcycle_safe: true, images: ['/sample-products/banana-chips-photo.png'], is_active: true },
  { sku: 'JOM-SAMPLE-CLEAN-1L', category_id: CATEGORY.home, name: 'Citrus Dishwashing Liquid 1L', description: 'Concentrated citrus dishwashing liquid in a sealed one-liter refill bottle. Suitable for household and small food-business supply.', price: 145, wholesale_price: 105, suggested_retail_price: 145, stock_quantity: 150, min_order_qty: 6, discount_tiers: [{ min_qty: 24, discount_percent: 6, price: 98.7 }, { min_qty: 48, discount_percent: 10, price: 94.5 }], packed_weight_kg: 1.08, packed_length_cm: 10, packed_width_cm: 10, packed_height_cm: 28, product_type: 'Household cleaning liquid', fragile: false, keep_upright: true, motorcycle_safe: true, images: ['/sample-products/dishwashing-liquid-photo.png'], is_active: true },
  { sku: 'JOM-SAMPLE-EARBUDS', category_id: CATEGORY.electronics, name: 'Wireless Earbuds Pro', description: 'True wireless earbuds with active noise cancellation and a compact charging case. A high-demand, easy-to-resell electronics item.', price: 1299, wholesale_price: 950, suggested_retail_price: 1299, stock_quantity: 60, min_order_qty: 1, discount_tiers: [{ min_qty: 5, discount_percent: 5, price: 902.5 }, { min_qty: 12, discount_percent: 9, price: 864.5 }], packed_weight_kg: 0.15, packed_length_cm: 12, packed_width_cm: 9, packed_height_cm: 5, product_type: 'Electronics accessory', fragile: true, keep_upright: false, motorcycle_safe: true, images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80'], is_active: true },
  { sku: 'JOM-SAMPLE-TEE', category_id: CATEGORY.fashion, name: 'Everyday Cotton Tee (3-Pack)', description: 'Soft, breathable 100% cotton t-shirts in a resale-ready 3-pack. A wardrobe staple that moves fast in any storefront.', price: 249, wholesale_price: 175, suggested_retail_price: 249, stock_quantity: 200, min_order_qty: 3, discount_tiers: [{ min_qty: 12, discount_percent: 6, price: 164.5 }, { min_qty: 24, discount_percent: 10, price: 157.5 }], packed_weight_kg: 0.2, packed_length_cm: 25, packed_width_cm: 20, packed_height_cm: 3, product_type: 'Apparel', fragile: false, keep_upright: false, motorcycle_safe: true, images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80'], is_active: true },
]
