import { TrendingUp } from 'lucide-react'
import { getResellerProfitEstimate } from '../../utils/pricing'
import { peso } from '../../utils/format'

export default function ProductProfitPreview({ form }) {
  const buyingPrice=Number(form.wholesale_price||form.price)||0, sellingPrice=Number(form.suggested_retail_price||form.price)||0
  if(!buyingPrice||!sellingPrice)return <section className="rounded-2xl border border-dashed border-mango-300 bg-mango-100/30 p-5 text-center"><TrendingUp className="mx-auto text-mango-600"/><h2 className="mt-2 font-display font-bold text-ink">Reseller Earnings Preview</h2><p className="mt-1 text-xs text-ink/50">Enter the buying and suggested selling prices to see the Reseller's estimated earnings.</p></section>
  const tiers=(form.discount_tiers||[]).filter(t=>Number(t.min_qty)>=2&&Number(t.discount_percent)>0).map(t=>({min_qty:Number(t.min_qty),price:Number((buyingPrice*(1-Number(t.discount_percent)/100)).toFixed(2))}))
  const product={price:Number(form.price)||buyingPrice,wholesale_price:buyingPrice,suggested_retail_price:sellingPrice,discount_tiers:tiers}
  const quantities=[1,Number(form.min_order_qty)||1,...tiers.map(t=>t.min_qty)].filter((v,i,a)=>v>0&&a.indexOf(v)===i).sort((a,b)=>a-b)
  return <section className="overflow-hidden rounded-2xl border-2 border-mango-300 bg-white shadow-lg shadow-mango-500/10"><header className="bg-gradient-to-r from-teal-950 to-teal-700 p-4 text-white"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-mango-400 text-ink"><TrendingUp size={20}/></span><div><h2 className="font-display text-lg font-bold">Reseller Earnings Preview</h2><p className="text-[11px] text-white/65">Shown to Merchant and Admin before saving</p></div></div></header><div className="p-4"><div className="grid gap-3 sm:grid-cols-2">{quantities.map(quantity=>{const e=getResellerProfitEstimate(product,quantity,sellingPrice),margin=e.customerTotal?e.estimatedProfit/e.customerTotal*100:0;return <article key={quantity} className={`rounded-2xl border p-4 ${e.estimatedProfit>0?'border-teal-100 bg-teal-50':'border-coral-200 bg-coral-50'}`}><div className="flex items-start justify-between gap-2"><div><p className="text-[10px] font-bold uppercase tracking-wide text-ink/40">{quantity===1?'One-piece sale':`${quantity}-piece bulk sale`}</p><p className="mt-1 font-display text-xl font-extrabold text-teal-800">{peso(e.estimatedProfit)}</p><p className="text-[10px] font-semibold text-teal-700">Estimated Reseller profit</p></div><span className="rounded-full bg-white px-2 py-1 text-[10px] font-bold text-ink/60">{margin.toFixed(1)}%</span></div><div className="mt-3 grid grid-cols-2 gap-2 border-t border-black/[.06] pt-3 text-xs"><div><p className="text-ink/40">Buying price</p><p className="font-bold">{peso(e.buyingUnitPrice)} each</p></div><div><p className="text-ink/40">Selling price</p><p className="font-bold">{peso(e.sellingUnitPrice)} each</p></div><div><p className="text-ink/40">Buying subtotal</p><p className="font-bold">{peso(e.buyingSubtotal)}</p></div><div><p className="text-ink/40">Customer total</p><p className="font-bold">{peso(e.customerTotal)}</p></div><div><p className="text-ink/40">System fee</p><p className="font-bold text-mango-700">{peso(e.systemFee)}</p></div><div><p className="text-ink/40">Gross before fee</p><p className="font-bold">{peso(e.grossProfit)}</p></div></div></article>})}</div><p className="mt-3 rounded-xl bg-cream px-3 py-2 text-[10px] leading-4 text-ink/50">Based on the suggested selling price and capped 1% system fee (₱3 minimum, ₱50 maximum per order), before delivery, marketing, returns, and taxes.</p></div></section>
}
